import type { Building, MetreXY } from "./types";
import { bbox } from "./geo";
import { isSpace, isNonRoutable } from "./categories";

// Demo "irregular casino": a curved, no-right-angles gaming floor (Level 0) — a
// central curved concourse ringed by 8 gaming-zone wedges with structural columns
// casting real occlusion shadows, plus a customer-facing Cage — over a rectangular
// staff back-of-house (Level 1: Surveillance / Count Room / Vault / Server /
// Records / Ops), restricted-heavy. Casino-doctrine cameras (dome blanket,
// per-zone domes, cage/vault overlap, Count Room 100%) give ~98% floor + 100% BOH
// coverage, verified by the occlusion engine. Generated by scratch/_scratch-gen-casino.mjs.

/** Axis-aligned rectangle as a 4-vertex polygon (open ring). */
export function rectPoly(x0: number, y0: number, x1: number, y1: number): MetreXY[] {
  return [
    [x0, y0],
    [x1, y0],
    [x1, y1],
    [x0, y1],
  ];
}

/** A rectangle polygon from any two drag corners. */
export function rectFromDrag(a: MetreXY, b: MetreXY): MetreXY[] {
  return rectPoly(
    Math.min(a[0], b[0]),
    Math.min(a[1], b[1]),
    Math.max(a[0], b[0]),
    Math.max(a[1], b[1]),
  );
}

export const initialBuilding: Building = {
  origin: [-115.1728,36.1147],
  levels: [{"ordinal":0,"name":"Gaming Floor"},{"ordinal":1,"name":"Surveillance & BOH"}],
  units: [
    {"id":"concourse","ordinal":0,"name":"Main Concourse","category":"corridor","polygon":[[69,45],[70.23,49.08],[69.29,53.25],[66.15,56.15],[62,57.12],[58.17,56.82],[55,56.5],[51.83,56.82],[48,57.12],[43.85,56.15],[40.71,53.25],[39.77,49.08],[41,45],[43.18,41.83],[45.04,39.25],[46.35,36.35],[48,32.88],[50.92,29.77],[55,28.5],[59.08,29.77],[62,32.88],[63.65,36.35],[64.96,39.25],[66.82,41.83]]},
    {"id":"zone-0","ordinal":0,"name":"Slots North","category":"room","polygon":[[44.5,70.99],[41.01,69.34],[37.54,67.51],[34.07,65.43],[30.62,62.98],[27.28,60.05],[40.51,52.87],[41.83,54.71],[43.67,56.06],[45.81,56.85],[48.03,57.13],[50.14,57.04]]},
    {"id":"zone-1","ordinal":0,"name":"Slots West","category":"room","polygon":[[27.28,60.05],[24.21,56.57],[21.58,52.53],[19.59,47.97],[18.44,43.02],[18.27,37.86],[42.59,42.59],[41.42,44.26],[40.43,46.22],[39.84,48.42],[39.83,50.7],[40.51,52.87]]},
    {"id":"zone-2","ordinal":0,"name":"The Lounge","category":"room","polygon":[[18.27,37.86],[19.16,32.73],[21.09,27.87],[23.99,23.53],[27.7,19.9],[32.01,17.11],[46.85,35.12],[46.15,36.86],[45.48,38.41],[44.7,39.8],[43.73,41.14],[42.59,42.59]]},
    {"id":"zone-3","ordinal":0,"name":"Table Games","category":"room","polygon":[[32.01,17.11],[36.68,15.22],[41.48,14.19],[46.21,13.95],[50.75,14.34],[55,15.21],[55,28.5],[52.76,28.87],[50.73,29.9],[49.05,31.44],[47.77,33.25],[46.85,35.12]]},
    {"id":"zone-4","ordinal":0,"name":"High Limit Salon","category":"room","polygon":[[55,15.21],[58.97,16.41],[62.69,17.81],[66.26,19.36],[69.74,21.04],[73.21,22.91],[63.15,35.12],[62.23,33.25],[60.95,31.44],[59.27,29.9],[57.24,28.87],[55,28.5]],"security":"secure"},
    {"id":"zone-5","ordinal":0,"name":"Poker Room","category":"room","polygon":[[73.21,22.91],[76.68,25.06],[80.11,27.61],[83.41,30.65],[86.4,34.25],[88.91,38.41],[67.41,42.59],[66.27,41.14],[65.3,39.8],[64.52,38.41],[63.85,36.86],[63.15,35.12]]},
    {"id":"zone-6","ordinal":0,"name":"Sportsbook","category":"room","polygon":[[88.91,38.41],[90.73,43.06],[91.68,48.08],[91.63,53.25],[90.52,58.35],[88.36,63.11],[69.49,52.87],[70.17,50.7],[70.16,48.42],[69.57,46.22],[68.58,44.26],[67.41,42.59]]},
    {"id":"zone-7","ordinal":0,"name":"Slots East","category":"room","polygon":[[88.36,63.11],[85.27,67.32],[81.41,70.78],[77.01,73.37],[72.29,75.08],[67.49,75.92],[59.86,57.04],[61.97,57.13],[64.19,56.85],[66.33,56.06],[68.17,54.71],[69.49,52.87]]},
    {"id":"cage","ordinal":0,"name":"The Cage","category":"room","security":"secure","polygon":[[61.8,65.92],[59.12,66.61],[56.38,66.96],[53.62,66.96],[50.88,66.61],[48.2,65.92],[51.13,56.92],[52.77,56.68],[54.28,56.52],[55.72,56.52],[57.23,56.68],[58.87,56.92]]},
    {"id":"col-0","ordinal":0,"name":"Column 1","category":"mechanical","security":"restricted","polygon":[[38.67,62.49],[40.47,62.49],[40.47,64.29],[38.67,64.29]]},
    {"id":"col-1","ordinal":0,"name":"Column 2","category":"mechanical","security":"restricted","polygon":[[30.19,46.19],[31.99,46.19],[31.99,47.99],[30.19,47.99]]},
    {"id":"col-2","ordinal":0,"name":"Column 3","category":"mechanical","security":"restricted","polygon":[[32.8,29.19],[34.6,29.19],[34.6,30.99],[32.8,30.99]]},
    {"id":"col-3","ordinal":0,"name":"Column 4","category":"mechanical","security":"restricted","polygon":[[47.89,20.92],[49.69,20.92],[49.69,22.72],[47.89,22.72]]},
    {"id":"col-4","ordinal":0,"name":"Column 5","category":"mechanical","security":"restricted","polygon":[[67.1,21.58],[68.9,21.58],[68.9,23.38],[67.1,23.38]]},
    {"id":"col-5","ordinal":0,"name":"Column 6","category":"mechanical","security":"restricted","polygon":[[76.65,35.89],[78.45,35.89],[78.45,37.69],[76.65,37.69]]},
    {"id":"col-6","ordinal":0,"name":"Column 7","category":"mechanical","security":"restricted","polygon":[[78.53,52.99],[80.33,52.99],[80.33,54.79],[78.53,54.79]]},
    {"id":"col-7","ordinal":0,"name":"Column 8","category":"mechanical","security":"restricted","polygon":[[66.1,64.88],[67.9,64.88],[67.9,66.68],[66.1,66.68]]},
    {"id":"stair-0","ordinal":0,"name":"Stairwell","category":"stairs","polygon":[[57,52],[63,52],[63,58],[57,58]]},
    {"id":"elev-0","ordinal":0,"name":"Service Elevator","category":"elevator","polygon":[[47,52],[53,52],[53,58],[47,58]]},
    {"id":"plaza","ordinal":0,"name":"Entrance Plaza","category":"outside","polygon":[[38,2],[72,2],[72,12],[38,12]]},
    {"id":"corr-1","ordinal":1,"name":"Service Corridor","category":"corridor","polygon":[[20,43],[90,43],[90,47],[20,47]]},
    {"id":"r1-0","ordinal":1,"name":"Surveillance Room","category":"room","polygon":[[20,47],[34,47],[34,62],[20,62]],"security":"restricted"},
    {"id":"r1-1","ordinal":1,"name":"Count Room","category":"room","polygon":[[34,47],[48,47],[48,62],[34,62]],"security":"restricted"},
    {"id":"r1-2","ordinal":1,"name":"Vault","category":"room","polygon":[[48,47],[62,47],[62,62],[48,62]],"security":"restricted"},
    {"id":"r1-3","ordinal":1,"name":"Server Room","category":"room","polygon":[[62,47],[76,47],[76,62],[62,62]],"security":"restricted"},
    {"id":"r1-4","ordinal":1,"name":"Records","category":"room","polygon":[[76,47],[90,47],[90,62],[76,62]],"security":"restricted"},
    {"id":"r1-5","ordinal":1,"name":"Security Ops","category":"room","polygon":[[20,28],[34,28],[34,43],[20,43]],"security":"secure"},
    {"id":"r1-6","ordinal":1,"name":"Surveillance Storage","category":"room","polygon":[[34,28],[48,28],[48,43],[34,43]],"security":"restricted"},
    {"id":"r1-7","ordinal":1,"name":"Executive Office","category":"room","polygon":[[48,28],[62,28],[62,43],[48,43]],"security":"secure"},
    {"id":"r1-8","ordinal":1,"name":"Staff Break Room","category":"room","polygon":[[62,28],[76,28],[76,43],[62,43]]},
    {"id":"r1-9","ordinal":1,"name":"Receiving","category":"room","polygon":[[76,28],[90,28],[90,43],[76,43]],"security":"secure"},
    {"id":"stair-1","ordinal":1,"name":"Stairwell","category":"stairs","polygon":[[90,47],[96,47],[96,53],[90,53]]},
    {"id":"elev-1","ordinal":1,"name":"Service Elevator","category":"elevator","polygon":[[90,37],[96,37],[96,43],[90,43]]},
  ],
  openings: [
    {"id":"d-zone-0","unit":"zone-0","at":[44.72,56.52]},
    {"id":"d-zone-1","unit":"zone-1","at":[40.07,47.3]},
    {"id":"d-zone-2","unit":"zone-2","at":[45.12,39.12]},
    {"id":"d-zone-3","unit":"zone-3","at":[49.84,30.62]},
    {"id":"d-zone-4","unit":"zone-4","at":[60.16,30.62]},
    {"id":"d-zone-5","unit":"zone-5","at":[64.88,39.12]},
    {"id":"d-zone-6","unit":"zone-6","at":[69.93,47.3]},
    {"id":"d-zone-7","unit":"zone-7","at":[65.28,56.52]},
    {"id":"d-cage","unit":"cage","at":[55,56.5]},
    {"id":"d-stair-0","unit":"stair-0","at":[60,52]},
    {"id":"d-elev-0","unit":"elev-0","at":[50,52]},
    {"id":"e-main","unit":"zone-3","at":[43.86,13.98],"kind":"entrance"},
    {"id":"d-r1-0","unit":"r1-0","at":[27,47]},
    {"id":"d-r1-1","unit":"r1-1","at":[41,47]},
    {"id":"d-r1-2","unit":"r1-2","at":[55,47]},
    {"id":"d-r1-3","unit":"r1-3","at":[69,47]},
    {"id":"d-r1-4","unit":"r1-4","at":[83,47]},
    {"id":"d-r1-5","unit":"r1-5","at":[27,43]},
    {"id":"d-r1-6","unit":"r1-6","at":[41,43]},
    {"id":"d-r1-7","unit":"r1-7","at":[55,43]},
    {"id":"d-r1-8","unit":"r1-8","at":[69,43]},
    {"id":"d-r1-9","unit":"r1-9","at":[83,43]},
    {"id":"d-stair-1","unit":"stair-1","at":[93,47]},
    {"id":"d-elev-1","unit":"elev-1","at":[93,43]},
  ],
  verticals: [{"a":"stair-0","b":"stair-1","name":"Stairs"},{"a":"elev-0","b":"elev-1","name":"Service Elevator"}],
  cameras: [
    {"id":"cam-0-1","ordinal":0,"at":[43.42,62.27],"heading":0,"fovDeg":360,"rangeM":18.040780935928307,"kind":"dome","name":"Slots North Dome 1","streamRef":"rtsp://10.0.1.10/main"},
    {"id":"cam-0-2","ordinal":0,"at":[39.15,58.47],"heading":0,"fovDeg":360,"rangeM":18.040780935928307,"kind":"dome","name":"Slots North Dome 2","streamRef":"rtsp://10.0.2.10/main"},
    {"id":"cam-0-3","ordinal":0,"at":[32.94,51.6],"heading":0,"fovDeg":360,"rangeM":22.855771577208458,"kind":"dome","name":"Slots West Dome 1","streamRef":"rtsp://10.0.3.10/main"},
    {"id":"cam-0-4","ordinal":0,"at":[31.97,45.34],"heading":0,"fovDeg":360,"rangeM":22.855771577208458,"kind":"dome","name":"Slots West Dome 2","streamRef":"rtsp://10.0.4.10/main"},
    {"id":"cam-0-5","ordinal":0,"at":[34.67,36.43],"heading":0,"fovDeg":360,"rangeM":27.798272085279464,"kind":"dome","name":"The Lounge Dome 1","streamRef":"rtsp://10.0.5.10/main"},
    {"id":"cam-0-6","ordinal":0,"at":[37.77,31.22],"heading":0,"fovDeg":360,"rangeM":27.798272085279464,"kind":"dome","name":"The Lounge Dome 2","streamRef":"rtsp://10.0.6.10/main"},
    {"id":"cam-0-7","ordinal":0,"at":[44.63,25.2],"heading":0,"fovDeg":360,"rangeM":21.258600955486628,"kind":"dome","name":"Table Games Dome 1","streamRef":"rtsp://10.0.7.10/main"},
    {"id":"cam-0-8","ordinal":0,"at":[50.41,23.13],"heading":0,"fovDeg":360,"rangeM":21.258600955486628,"kind":"dome","name":"Table Games Dome 2","streamRef":"rtsp://10.0.8.10/main"},
    {"id":"cam-0-9","ordinal":0,"at":[59.19,25.03],"heading":0,"fovDeg":360,"rangeM":17.604119560240697,"kind":"dome","name":"High Limit Salon Dome 1","streamRef":"rtsp://10.0.9.10/main"},
    {"id":"cam-0-10","ordinal":0,"at":[64.47,26.93],"heading":0,"fovDeg":360,"rangeM":17.604119560240697,"kind":"dome","name":"High Limit Salon Dome 2","streamRef":"rtsp://10.0.10.10/main"},
    {"id":"cam-0-11","ordinal":0,"at":[70.13,32.9],"heading":0,"fovDeg":360,"rangeM":22.749174842735243,"kind":"dome","name":"Poker Room Dome 1","streamRef":"rtsp://10.0.11.10/main"},
    {"id":"cam-0-12","ordinal":0,"at":[72.85,37.48],"heading":0,"fovDeg":360,"rangeM":22.749174842735243,"kind":"dome","name":"Poker Room Dome 2","streamRef":"rtsp://10.0.12.10/main"},
    {"id":"cam-0-13","ordinal":0,"at":[78.95,45.36],"heading":0,"fovDeg":360,"rangeM":24.583426627637692,"kind":"dome","name":"Sportsbook Dome 1","streamRef":"rtsp://10.0.13.10/main"},
    {"id":"cam-0-14","ordinal":0,"at":[77.95,51.86],"heading":0,"fovDeg":360,"rangeM":24.583426627637692,"kind":"dome","name":"Sportsbook Dome 2","streamRef":"rtsp://10.0.14.10/main"},
    {"id":"cam-0-15","ordinal":0,"at":[73.17,60.44],"heading":0,"fovDeg":360,"rangeM":23.749182427531764,"kind":"dome","name":"Slots East Dome 1","streamRef":"rtsp://10.0.15.10/main"},
    {"id":"cam-0-16","ordinal":0,"at":[68.28,64.8],"heading":0,"fovDeg":360,"rangeM":23.749182427531764,"kind":"dome","name":"Slots East Dome 2","streamRef":"rtsp://10.0.16.10/main"},
    {"id":"cam-0-17","ordinal":0,"at":[58.74,62.61],"heading":0,"fovDeg":360,"rangeM":11,"kind":"dome","name":"Cage Dome 1","streamRef":"rtsp://10.0.17.10/main"},
    {"id":"cam-0-18","ordinal":0,"at":[55,63],"heading":0,"fovDeg":360,"rangeM":11,"kind":"dome","name":"Cage Dome 2","streamRef":"rtsp://10.0.18.10/main"},
    {"id":"cam-0-19","ordinal":0,"at":[51.26,62.61],"heading":0,"fovDeg":360,"rangeM":11,"kind":"dome","name":"Cage Dome 3","streamRef":"rtsp://10.0.19.10/main"},
    {"id":"cam-0-20","ordinal":0,"at":[55,65],"heading":90,"fovDeg":90,"rangeM":12,"kind":"fixed","name":"Cage Teller","streamRef":"rtsp://10.0.20.10/main"},
    {"id":"cam-0-21","ordinal":0,"at":[55,45],"heading":0,"fovDeg":360,"rangeM":18,"kind":"dome","name":"Concourse Center","streamRef":"rtsp://10.0.21.10/main"},
    {"id":"cam-0-22","ordinal":0,"at":[59.5,52.79],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 1","streamRef":"rtsp://10.0.22.10/main"},
    {"id":"cam-0-23","ordinal":0,"at":[46,45],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 2","streamRef":"rtsp://10.0.23.10/main"},
    {"id":"cam-0-24","ordinal":0,"at":[59.5,37.21],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 3","streamRef":"rtsp://10.0.24.10/main"},
    {"id":"cam-0-25","ordinal":0,"at":[60,55],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Stairwell Cam L0","streamRef":"rtsp://10.0.25.10/main"},
    {"id":"cam-0-26","ordinal":0,"at":[50,55],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Elevator Cam L0","streamRef":"rtsp://10.0.26.10/main"},
    {"id":"cam-0-27","ordinal":0,"at":[43.86,16.98],"heading":-90,"fovDeg":80,"rangeM":12,"kind":"fixed","name":"Main Entrance","streamRef":"rtsp://10.0.27.10/main"},
    {"id":"cam-1-28","ordinal":1,"at":[20.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Surveillance Room Cam","streamRef":"rtsp://10.1.28.10/main"},
    {"id":"cam-1-29","ordinal":1,"at":[30.5,50.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Surveillance Dome","streamRef":"rtsp://10.1.29.10/main"},
    {"id":"cam-1-30","ordinal":1,"at":[34.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Count Room Cam","streamRef":"rtsp://10.1.30.10/main"},
    {"id":"cam-1-31","ordinal":1,"at":[37.5,58.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Count Room Dome NW","streamRef":"rtsp://10.1.31.10/main"},
    {"id":"cam-1-32","ordinal":1,"at":[44.5,58.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Count Room Dome NE","streamRef":"rtsp://10.1.32.10/main"},
    {"id":"cam-1-33","ordinal":1,"at":[37.5,50.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Count Room Dome SW","streamRef":"rtsp://10.1.33.10/main"},
    {"id":"cam-1-34","ordinal":1,"at":[48.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Vault Cam","streamRef":"rtsp://10.1.34.10/main"},
    {"id":"cam-1-35","ordinal":1,"at":[58.5,58.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Vault Dome","streamRef":"rtsp://10.1.35.10/main"},
    {"id":"cam-1-36","ordinal":1,"at":[51.5,50.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Vault Dome 2","streamRef":"rtsp://10.1.36.10/main"},
    {"id":"cam-1-37","ordinal":1,"at":[62.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Server Room Cam","streamRef":"rtsp://10.1.37.10/main"},
    {"id":"cam-1-38","ordinal":1,"at":[76.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Records Cam","streamRef":"rtsp://10.1.38.10/main"},
    {"id":"cam-1-39","ordinal":1,"at":[20.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Security Ops Cam","streamRef":"rtsp://10.1.39.10/main"},
    {"id":"cam-1-40","ordinal":1,"at":[34.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Surveillance Storage Cam","streamRef":"rtsp://10.1.40.10/main"},
    {"id":"cam-1-41","ordinal":1,"at":[48.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Executive Office Cam","streamRef":"rtsp://10.1.41.10/main"},
    {"id":"cam-1-42","ordinal":1,"at":[62.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Staff Break Room Cam","streamRef":"rtsp://10.1.42.10/main"},
    {"id":"cam-1-43","ordinal":1,"at":[76.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Receiving Cam","streamRef":"rtsp://10.1.43.10/main"},
    {"id":"cam-1-44","ordinal":1,"at":[30,45],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Service Corridor W","streamRef":"rtsp://10.1.44.10/main"},
    {"id":"cam-1-45","ordinal":1,"at":[55,45],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Service Corridor C","streamRef":"rtsp://10.1.45.10/main"},
    {"id":"cam-1-46","ordinal":1,"at":[80,45],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Service Corridor E","streamRef":"rtsp://10.1.46.10/main"},
    {"id":"cam-1-47","ordinal":1,"at":[93,50],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Stairwell Cam L1","streamRef":"rtsp://10.1.47.10/main"},
    {"id":"cam-1-48","ordinal":1,"at":[93,40],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Elevator Cam L1","streamRef":"rtsp://10.1.48.10/main"},
  ],
  incidents: [
    {"id":"inc-1","ordinal":0,"at":[48.79,21.82],"kind":"theft","note":"Chip dispute flagged at Table Games."},
    {"id":"inc-2","ordinal":0,"at":[18,90],"kind":"alarm","note":"Cage drawer alarm 01:52."},
    {"id":"inc-3","ordinal":1,"at":[41,55],"kind":"trespass","note":"Unescorted contractor near Count Room."},
  ],
  patrols: [
    {"id":"patrol-0","ordinal":0,"name":"Floor Sweep","points":[[55,56.5],[55,45],[37.68,35],[45.42,18.69],[72.32,35]]},
    {"id":"patrol-1","ordinal":1,"name":"BOH Sweep","points":[[22,45],[55,45],[88,45]]},
  ],
};

/**
 * Units a user can pick as a route start/destination: every authored space
 * (room/office/restroom/lobby/retail/storage/mechanical/outside), excluding
 * circulation (corridor/elevator/stairs) and security-restricted units.
 */
export function selectableUnits(b: Building) {
  return b.units.filter((u) => isSpace(u.category) && !isNonRoutable(u));
}

/**
 * Place a door for a freshly-authored room: on the room's bounding-box edge
 * nearest the corridor, horizontally centred but clamped to the corridor's
 * extent. Good enough for the spike; doors become draggable next.
 */
export function doorForRoom(
  b: Building,
  polygon: MetreXY[],
  ordinal: number,
): MetreXY | null {
  const corridor = b.units.find((u) => u.category === "corridor" && u.ordinal === ordinal);
  if (!corridor) return null;
  const [cx0, cy0, cx1, cy1] = bbox(corridor.polygon);
  const [x0, y0, x1, y1] = bbox(polygon);
  const cx = Math.min(Math.max((x0 + x1) / 2, cx0), cx1);
  // Below the corridor band -> door on corridor's bottom edge; above -> top edge.
  if (y1 <= cy0) return [cx, cy0];
  if (y0 >= cy1) return [cx, cy1];
  return [cx, cy0];
}
