import type { Building, MetreXY } from "./types";
import { bbox } from "./geo";
import { isSpace, isNonRoutable } from "./categories";

// Demo "irregular casino": a curved, no-right-angles gaming floor (Level 0) — a
// central curved concourse ringed by 8 gaming-zone wedges with structural columns
// casting real occlusion shadows, plus a customer-facing Cage — over a rectangular
// staff back-of-house (Level 1: Surveillance / Count Room / Vault / Server /
// Records / Ops), restricted-heavy. Casino-doctrine cameras (dome blanket,
// per-zone domes, cage/vault overlap, Count Room 100%) give ~98% floor + 100% BOH
// coverage, verified by the occlusion engine. Generated by scratch/_scratch-gen-casino.mjs.

/** Axis-aligned rectangle as a 4-vertex polygon (open ring). */
export function rectPoly(x0: number, y0: number, x1: number, y1: number): MetreXY[] {
  return [
    [x0, y0],
    [x1, y0],
    [x1, y1],
    [x0, y1],
  ];
}

/** A rectangle polygon from any two drag corners. */
export function rectFromDrag(a: MetreXY, b: MetreXY): MetreXY[] {
  return rectPoly(
    Math.min(a[0], b[0]),
    Math.min(a[1], b[1]),
    Math.max(a[0], b[0]),
    Math.max(a[1], b[1]),
  );
}

export const initialBuilding: Building = {
  origin: [-115.1728,36.1147],
  levels: [{"ordinal":0,"name":"Gaming Floor"},{"ordinal":1,"name":"Surveillance & BOH"}],
  units: [
    {"id":"concourse","ordinal":0,"name":"Main Concourse","category":"corridor","polygon":[[69,45],[69.69,46.54],[70.13,48.22],[70.24,49.95],[69.96,51.66],[69.29,53.25],[68.25,54.63],[66.91,55.72],[65.35,56.5],[63.68,56.95],[62,57.12],[60.38,57.08],[58.87,56.92],[57.49,56.72],[56.21,56.56],[55,56.5],[53.79,56.56],[52.51,56.72],[51.13,56.92],[49.62,57.08],[48,57.12],[46.32,56.95],[44.65,56.5],[43.09,55.72],[41.75,54.63],[40.71,53.25],[40.04,51.66],[39.76,49.95],[39.87,48.22],[40.31,46.54],[41,45],[41.85,43.62],[42.74,42.39],[43.61,41.3],[44.38,40.27],[45.04,39.25],[45.6,38.17],[46.1,36.99],[46.62,35.69],[47.23,34.3],[48,32.88],[48.99,31.5],[50.22,30.29],[51.67,29.33],[53.29,28.71],[55,28.5],[56.71,28.71],[58.33,29.33],[59.78,30.29],[61.01,31.5],[62,32.88],[62.77,34.3],[63.38,35.69],[63.9,36.99],[64.4,38.17],[64.96,39.25],[65.62,40.27],[66.39,41.3],[67.26,42.39],[68.15,43.62]]},
    {"id":"zone-0","ordinal":0,"name":"Slots North","category":"room","polygon":[[44.5,70.99],[42.75,70.18],[41.01,69.34],[39.27,68.45],[37.54,67.51],[35.8,66.51],[34.07,65.43],[32.34,64.25],[30.62,62.98],[28.93,61.58],[27.28,60.05],[40.51,52.87],[41.09,53.84],[41.83,54.71],[42.7,55.45],[43.67,56.06],[44.72,56.52],[45.81,56.85],[46.92,57.04],[48.03,57.13],[49.1,57.12],[50.14,57.04]]},
    {"id":"zone-1","ordinal":0,"name":"Slots West","category":"room","polygon":[[27.28,60.05],[25.7,58.38],[24.21,56.57],[22.82,54.62],[21.58,52.53],[20.49,50.31],[19.59,47.97],[18.91,45.54],[18.44,43.02],[18.23,40.45],[18.27,37.86],[42.59,42.59],[42,43.39],[41.42,44.26],[40.89,45.21],[40.43,46.22],[40.07,47.3],[39.84,48.42],[39.75,49.56],[39.83,50.7],[40.08,51.81],[40.51,52.87]]},
    {"id":"zone-2","ordinal":0,"name":"The Lounge","category":"room","polygon":[[18.27,37.86],[18.58,35.28],[19.16,32.73],[20,30.25],[21.09,27.87],[22.43,25.62],[23.99,23.53],[25.76,21.61],[27.7,19.9],[29.79,18.39],[32.01,17.11],[46.85,35.12],[46.49,36.01],[46.15,36.86],[45.82,37.66],[45.48,38.41],[45.12,39.12],[44.7,39.8],[44.24,40.47],[43.73,41.14],[43.18,41.84],[42.59,42.59]]},
    {"id":"zone-3","ordinal":0,"name":"Table Games","category":"room","polygon":[[32.01,17.11],[34.31,16.05],[36.68,15.22],[39.07,14.6],[41.48,14.19],[43.86,13.98],[46.21,13.95],[48.51,14.08],[50.75,14.34],[52.91,14.73],[55,15.21],[55,28.5],[53.87,28.59],[52.76,28.87],[51.71,29.31],[50.73,29.9],[49.84,30.62],[49.05,31.44],[48.36,32.33],[47.77,33.25],[47.28,34.19],[46.85,35.12]]},
    {"id":"zone-4","ordinal":0,"name":"High Limit Salon","category":"room","polygon":[[55,15.21],[57.02,15.78],[58.97,16.41],[60.86,17.09],[62.69,17.81],[64.49,18.57],[66.26,19.36],[68,20.18],[69.74,21.04],[71.47,21.95],[73.21,22.91],[63.15,35.12],[62.72,34.19],[62.23,33.25],[61.64,32.33],[60.95,31.44],[60.16,30.62],[59.27,29.9],[58.29,29.31],[57.24,28.87],[56.13,28.59],[55,28.5]],"security":"secure"},
    {"id":"zone-5","ordinal":0,"name":"Poker Room","category":"room","polygon":[[73.21,22.91],[74.95,23.95],[76.68,25.06],[78.41,26.28],[80.11,27.61],[81.79,29.06],[83.41,30.65],[84.95,32.38],[86.4,34.25],[87.73,36.26],[88.91,38.41],[67.41,42.59],[66.82,41.84],[66.27,41.14],[65.76,40.47],[65.3,39.8],[64.88,39.12],[64.52,38.41],[64.18,37.66],[63.85,36.86],[63.51,36.01],[63.15,35.12]]},
    {"id":"zone-6","ordinal":0,"name":"Sportsbook","category":"room","polygon":[[88.91,38.41],[89.92,40.68],[90.73,43.06],[91.32,45.54],[91.68,48.08],[91.78,50.66],[91.63,53.25],[91.2,55.83],[90.52,58.35],[89.56,60.79],[88.36,63.11],[69.49,52.87],[69.92,51.81],[70.17,50.7],[70.25,49.56],[70.16,48.42],[69.93,47.3],[69.57,46.22],[69.11,45.21],[68.58,44.26],[68,43.39],[67.41,42.59]]},
    {"id":"zone-7","ordinal":0,"name":"Slots East","category":"room","polygon":[[88.36,63.11],[86.92,65.3],[85.27,67.32],[83.43,69.15],[81.41,70.78],[79.27,72.19],[77.01,73.37],[74.68,74.34],[72.29,75.08],[69.89,75.6],[67.49,75.92],[59.86,57.04],[60.9,57.12],[61.97,57.13],[63.08,57.04],[64.19,56.85],[65.28,56.52],[66.33,56.06],[67.3,55.45],[68.17,54.71],[68.91,53.84],[69.49,52.87]]},
    {"id":"cage","ordinal":0,"name":"The Cage","category":"room","security":"secure","polygon":[[61.8,65.92],[60.14,66.39],[58.44,66.73],[56.73,66.93],[55,67],[53.27,66.93],[51.56,66.73],[49.86,66.39],[48.2,65.92],[51.13,56.92],[52.18,56.76],[53.16,56.63],[54.09,56.53],[55,56.5],[55.91,56.53],[56.84,56.63],[57.82,56.76],[58.87,56.92]]},
    {"id":"col-0","ordinal":0,"name":"Column 1","category":"mechanical","security":"restricted","polygon":[[38.67,62.49],[40.47,62.49],[40.47,64.29],[38.67,64.29]]},
    {"id":"col-1","ordinal":0,"name":"Column 2","category":"mechanical","security":"restricted","polygon":[[30.19,46.19],[31.99,46.19],[31.99,47.99],[30.19,47.99]]},
    {"id":"col-2","ordinal":0,"name":"Column 3","category":"mechanical","security":"restricted","polygon":[[32.8,29.19],[34.6,29.19],[34.6,30.99],[32.8,30.99]]},
    {"id":"col-3","ordinal":0,"name":"Column 4","category":"mechanical","security":"restricted","polygon":[[47.89,20.92],[49.69,20.92],[49.69,22.72],[47.89,22.72]]},
    {"id":"col-4","ordinal":0,"name":"Column 5","category":"mechanical","security":"restricted","polygon":[[67.1,21.58],[68.9,21.58],[68.9,23.38],[67.1,23.38]]},
    {"id":"col-5","ordinal":0,"name":"Column 6","category":"mechanical","security":"restricted","polygon":[[76.65,35.89],[78.45,35.89],[78.45,37.69],[76.65,37.69]]},
    {"id":"col-6","ordinal":0,"name":"Column 7","category":"mechanical","security":"restricted","polygon":[[78.53,52.99],[80.33,52.99],[80.33,54.79],[78.53,54.79]]},
    {"id":"col-7","ordinal":0,"name":"Column 8","category":"mechanical","security":"restricted","polygon":[[66.1,64.88],[67.9,64.88],[67.9,66.68],[66.1,66.68]]},
    {"id":"stair-0","ordinal":0,"name":"Stairwell","category":"stairs","polygon":[[57,52],[63,52],[63,58],[57,58]]},
    {"id":"elev-0","ordinal":0,"name":"Service Elevator","category":"elevator","polygon":[[47,52],[53,52],[53,58],[47,58]]},
    {"id":"plaza","ordinal":0,"name":"Entrance Plaza","category":"outside","polygon":[[38,2],[72,2],[72,12],[38,12]]},
    {"id":"corr-1","ordinal":1,"name":"Service Corridor","category":"corridor","polygon":[[20,43],[90,43],[90,47],[20,47]]},
    {"id":"r1-0","ordinal":1,"name":"Surveillance Room","category":"room","polygon":[[20,47],[34,47],[34,62],[20,62]],"security":"restricted"},
    {"id":"r1-1","ordinal":1,"name":"Count Room","category":"room","polygon":[[34,47],[48,47],[48,62],[34,62]],"security":"restricted"},
    {"id":"r1-2","ordinal":1,"name":"Vault","category":"room","polygon":[[48,47],[62,47],[62,62],[48,62]],"security":"restricted"},
    {"id":"r1-3","ordinal":1,"name":"Server Room","category":"room","polygon":[[62,47],[76,47],[76,62],[62,62]],"security":"restricted"},
    {"id":"r1-4","ordinal":1,"name":"Records","category":"room","polygon":[[76,47],[90,47],[90,62],[76,62]],"security":"restricted"},
    {"id":"r1-5","ordinal":1,"name":"Security Ops","category":"room","polygon":[[20,28],[34,28],[34,43],[20,43]],"security":"secure"},
    {"id":"r1-6","ordinal":1,"name":"Surveillance Storage","category":"room","polygon":[[34,28],[48,28],[48,43],[34,43]],"security":"restricted"},
    {"id":"r1-7","ordinal":1,"name":"Executive Office","category":"room","polygon":[[48,28],[62,28],[62,43],[48,43]],"security":"secure"},
    {"id":"r1-8","ordinal":1,"name":"Staff Break Room","category":"room","polygon":[[62,28],[76,28],[76,43],[62,43]]},
    {"id":"r1-9","ordinal":1,"name":"Receiving","category":"room","polygon":[[76,28],[90,28],[90,43],[76,43]],"security":"secure"},
    {"id":"stair-1","ordinal":1,"name":"Stairwell","category":"stairs","polygon":[[90,47],[96,47],[96,53],[90,53]]},
    {"id":"elev-1","ordinal":1,"name":"Service Elevator","category":"elevator","polygon":[[90,37],[96,37],[96,43],[90,43]]},
  ],
  openings: [
    {"id":"d-zone-0","unit":"zone-0","at":[44.72,56.52]},
    {"id":"d-zone-1","unit":"zone-1","at":[40.07,47.3]},
    {"id":"d-zone-2","unit":"zone-2","at":[45.12,39.12]},
    {"id":"d-zone-3","unit":"zone-3","at":[49.84,30.62]},
    {"id":"d-zone-4","unit":"zone-4","at":[60.16,30.62]},
    {"id":"d-zone-5","unit":"zone-5","at":[64.88,39.12]},
    {"id":"d-zone-6","unit":"zone-6","at":[69.93,47.3]},
    {"id":"d-zone-7","unit":"zone-7","at":[65.28,56.52]},
    {"id":"d-cage","unit":"cage","at":[55,56.5]},
    {"id":"d-stair-0","unit":"stair-0","at":[60,52]},
    {"id":"d-elev-0","unit":"elev-0","at":[50,52]},
    {"id":"e-main","unit":"zone-3","at":[43.86,13.98],"kind":"entrance"},
    {"id":"d-r1-0","unit":"r1-0","at":[27,47]},
    {"id":"d-r1-1","unit":"r1-1","at":[41,47]},
    {"id":"d-r1-2","unit":"r1-2","at":[55,47]},
    {"id":"d-r1-3","unit":"r1-3","at":[69,47]},
    {"id":"d-r1-4","unit":"r1-4","at":[83,47]},
    {"id":"d-r1-5","unit":"r1-5","at":[27,43]},
    {"id":"d-r1-6","unit":"r1-6","at":[41,43]},
    {"id":"d-r1-7","unit":"r1-7","at":[55,43]},
    {"id":"d-r1-8","unit":"r1-8","at":[69,43]},
    {"id":"d-r1-9","unit":"r1-9","at":[83,43]},
    {"id":"d-stair-1","unit":"stair-1","at":[93,47]},
    {"id":"d-elev-1","unit":"elev-1","at":[93,43]},
  ],
  verticals: [{"a":"stair-0","b":"stair-1","name":"Stairs"},{"a":"elev-0","b":"elev-1","name":"Service Elevator"}],
  cameras: [
    {"id":"cam-0-1","ordinal":0,"at":[42.04,59.52],"heading":0,"fovDeg":360,"rangeM":12.693853957285537,"kind":"dome","name":"Slots North Dome 1","streamRef":"rtsp://10.0.1.10/main"},
    {"id":"cam-0-2","ordinal":0,"at":[42.96,65.93],"heading":0,"fovDeg":360,"rangeM":15.032624748742645,"kind":"dome","name":"Slots North Dome 2","streamRef":"rtsp://10.0.2.10/main"},
    {"id":"cam-0-3","ordinal":0,"at":[35.57,59.33],"heading":0,"fovDeg":360,"rangeM":15.032624748742645,"kind":"dome","name":"Slots North Dome 3","streamRef":"rtsp://10.0.3.10/main"},
    {"id":"cam-0-4","ordinal":0,"at":[36.69,65.51],"heading":0,"fovDeg":360,"rangeM":14.693853957285537,"kind":"dome","name":"Slots North Dome 4","streamRef":"rtsp://10.0.4.10/main"},
    {"id":"cam-0-5","ordinal":0,"at":[34.2,48.2],"heading":0,"fovDeg":360,"rangeM":15.903847718138973,"kind":"dome","name":"Slots West Dome 1","streamRef":"rtsp://10.0.5.10/main"},
    {"id":"cam-0-6","ordinal":0,"at":[28.81,54.84],"heading":0,"fovDeg":360,"rangeM":18.884617261766767,"kind":"dome","name":"Slots West Dome 2","streamRef":"rtsp://10.0.6.10/main"},
    {"id":"cam-0-7","ordinal":0,"at":[27.06,43.49],"heading":0,"fovDeg":360,"rangeM":18.884617261766767,"kind":"dome","name":"Slots West Dome 3","streamRef":"rtsp://10.0.7.10/main"},
    {"id":"cam-0-8","ordinal":0,"at":[22.45,50.01],"heading":0,"fovDeg":360,"rangeM":17.903847718138973,"kind":"dome","name":"Slots West Dome 4","streamRef":"rtsp://10.0.8.10/main"},
    {"id":"cam-0-9","ordinal":0,"at":[38.31,35.07],"heading":0,"fovDeg":360,"rangeM":19.198848056852977,"kind":"dome","name":"The Lounge Dome 1","streamRef":"rtsp://10.0.9.10/main"},
    {"id":"cam-0-10","ordinal":0,"at":[27.88,35.72],"heading":0,"fovDeg":360,"rangeM":22.83861766822357,"kind":"dome","name":"The Lounge Dome 2","streamRef":"rtsp://10.0.10.10/main"},
    {"id":"cam-0-11","ordinal":0,"at":[33.9,25.6],"heading":0,"fovDeg":360,"rangeM":22.83861766822357,"kind":"dome","name":"The Lounge Dome 3","streamRef":"rtsp://10.0.11.10/main"},
    {"id":"cam-0-12","ordinal":0,"at":[24.7,26.97],"heading":0,"fovDeg":360,"rangeM":21.198848056852977,"kind":"dome","name":"The Lounge Dome 4","streamRef":"rtsp://10.0.12.10/main"},
    {"id":"cam-0-13","ordinal":0,"at":[48.05,25.63],"heading":0,"fovDeg":360,"rangeM":14.839067303657753,"kind":"dome","name":"Table Games Dome 1","streamRef":"rtsp://10.0.13.10/main"},
    {"id":"cam-0-14","ordinal":0,"at":[40.97,22.2],"heading":0,"fovDeg":360,"rangeM":17.606880764389302,"kind":"dome","name":"Table Games Dome 2","streamRef":"rtsp://10.0.14.10/main"},
    {"id":"cam-0-15","ordinal":0,"at":[51.32,18.49],"heading":0,"fovDeg":360,"rangeM":17.606880764389302,"kind":"dome","name":"Table Games Dome 3","streamRef":"rtsp://10.0.15.10/main"},
    {"id":"cam-0-16","ordinal":0,"at":[44.46,15.65],"heading":0,"fovDeg":360,"rangeM":16.839067303657753,"kind":"dome","name":"Table Games Dome 4","streamRef":"rtsp://10.0.16.10/main"},
    {"id":"cam-0-17","ordinal":0,"at":[61.46,27],"heading":0,"fovDeg":360,"rangeM":12.402746373493798,"kind":"dome","name":"High Limit Salon Dome 1","streamRef":"rtsp://10.0.17.10/main"},
    {"id":"cam-0-18","ordinal":0,"at":[58.24,21.62],"heading":0,"fovDeg":360,"rangeM":14.683295648192559,"kind":"dome","name":"High Limit Salon Dome 2","streamRef":"rtsp://10.0.18.10/main"},
    {"id":"cam-0-19","ordinal":0,"at":[67.37,24.9],"heading":0,"fovDeg":360,"rangeM":14.683295648192559,"kind":"dome","name":"High Limit Salon Dome 3","streamRef":"rtsp://10.0.19.10/main"},
    {"id":"cam-0-20","ordinal":0,"at":[64.06,19.77],"heading":0,"fovDeg":360,"rangeM":14.402746373493798,"kind":"dome","name":"High Limit Salon Dome 4","streamRef":"rtsp://10.0.20.10/main"},
    {"id":"cam-0-21","ordinal":0,"at":[69.96,36.1],"heading":0,"fovDeg":360,"rangeM":15.832783228490161,"kind":"dome","name":"Poker Room Dome 1","streamRef":"rtsp://10.0.21.10/main"},
    {"id":"cam-0-22","ordinal":0,"at":[72.88,28.56],"heading":0,"fovDeg":360,"rangeM":18.799339874188192,"kind":"dome","name":"Poker Room Dome 2","streamRef":"rtsp://10.0.22.10/main"},
    {"id":"cam-0-23","ordinal":0,"at":[77.98,37.13],"heading":0,"fovDeg":360,"rangeM":18.799339874188192,"kind":"dome","name":"Poker Room Dome 3","streamRef":"rtsp://10.0.23.10/main"},
    {"id":"cam-0-24","ordinal":0,"at":[80.1,30.07],"heading":0,"fovDeg":360,"rangeM":17.83278322849016,"kind":"dome","name":"Poker Room Dome 4","streamRef":"rtsp://10.0.24.10/main"},
    {"id":"cam-0-25","ordinal":0,"at":[76.49,48.31],"heading":0,"fovDeg":360,"rangeM":17.05561775175846,"kind":"dome","name":"Sportsbook Dome 1","streamRef":"rtsp://10.0.25.10/main"},
    {"id":"cam-0-26","ordinal":0,"at":[84.43,43.41],"heading":0,"fovDeg":360,"rangeM":20.266741302110155,"kind":"dome","name":"Sportsbook Dome 2","streamRef":"rtsp://10.0.26.10/main"},
    {"id":"cam-0-27","ordinal":0,"at":[82.59,55.37],"heading":0,"fovDeg":360,"rangeM":20.266741302110155,"kind":"dome","name":"Sportsbook Dome 3","streamRef":"rtsp://10.0.27.10/main"},
    {"id":"cam-0-28","ordinal":0,"at":[89.6,50.33],"heading":0,"fovDeg":360,"rangeM":19.05561775175846,"kind":"dome","name":"Sportsbook Dome 4","streamRef":"rtsp://10.0.28.10/main"},
    {"id":"cam-0-29","ordinal":0,"at":[69.48,61.22],"heading":0,"fovDeg":360,"rangeM":16.499454951687845,"kind":"dome","name":"Slots East Dome 1","streamRef":"rtsp://10.0.29.10/main"},
    {"id":"cam-0-30","ordinal":0,"at":[78.42,62.26],"heading":0,"fovDeg":360,"rangeM":19.599345942025412,"kind":"dome","name":"Slots East Dome 2","streamRef":"rtsp://10.0.30.10/main"},
    {"id":"cam-0-31","ordinal":0,"at":[69.5,70.22],"heading":0,"fovDeg":360,"rangeM":19.599345942025412,"kind":"dome","name":"Slots East Dome 3","streamRef":"rtsp://10.0.31.10/main"},
    {"id":"cam-0-32","ordinal":0,"at":[77.87,70.62],"heading":0,"fovDeg":360,"rangeM":18.499454951687845,"kind":"dome","name":"Slots East Dome 4","streamRef":"rtsp://10.0.32.10/main"},
    {"id":"cam-0-33","ordinal":0,"at":[58.74,62.61],"heading":0,"fovDeg":360,"rangeM":11,"kind":"dome","name":"Cage Dome 1","streamRef":"rtsp://10.0.33.10/main"},
    {"id":"cam-0-34","ordinal":0,"at":[55,63],"heading":0,"fovDeg":360,"rangeM":11,"kind":"dome","name":"Cage Dome 2","streamRef":"rtsp://10.0.34.10/main"},
    {"id":"cam-0-35","ordinal":0,"at":[51.26,62.61],"heading":0,"fovDeg":360,"rangeM":11,"kind":"dome","name":"Cage Dome 3","streamRef":"rtsp://10.0.35.10/main"},
    {"id":"cam-0-36","ordinal":0,"at":[55,65],"heading":90,"fovDeg":90,"rangeM":12,"kind":"fixed","name":"Cage Teller","streamRef":"rtsp://10.0.36.10/main"},
    {"id":"cam-0-37","ordinal":0,"at":[55,45],"heading":0,"fovDeg":360,"rangeM":18,"kind":"dome","name":"Concourse Center","streamRef":"rtsp://10.0.37.10/main"},
    {"id":"cam-0-38","ordinal":0,"at":[62.79,49.5],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 1","streamRef":"rtsp://10.0.38.10/main"},
    {"id":"cam-0-39","ordinal":0,"at":[51.92,53.46],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 2","streamRef":"rtsp://10.0.39.10/main"},
    {"id":"cam-0-40","ordinal":0,"at":[46.14,43.44],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 3","streamRef":"rtsp://10.0.40.10/main"},
    {"id":"cam-0-41","ordinal":0,"at":[55,36],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 4","streamRef":"rtsp://10.0.41.10/main"},
    {"id":"cam-0-42","ordinal":0,"at":[63.86,43.44],"heading":0,"fovDeg":360,"rangeM":16,"kind":"dome","name":"Concourse Dome 5","streamRef":"rtsp://10.0.42.10/main"},
    {"id":"cam-0-43","ordinal":0,"at":[60,55],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Stairwell Cam L0","streamRef":"rtsp://10.0.43.10/main"},
    {"id":"cam-0-44","ordinal":0,"at":[50,55],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Elevator Cam L0","streamRef":"rtsp://10.0.44.10/main"},
    {"id":"cam-0-45","ordinal":0,"at":[43.86,16.98],"heading":-90,"fovDeg":80,"rangeM":12,"kind":"fixed","name":"Main Entrance","streamRef":"rtsp://10.0.45.10/main"},
    {"id":"cam-1-46","ordinal":1,"at":[20.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Surveillance Room Cam","streamRef":"rtsp://10.1.46.10/main"},
    {"id":"cam-1-47","ordinal":1,"at":[30.5,50.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Surveillance Dome","streamRef":"rtsp://10.1.47.10/main"},
    {"id":"cam-1-48","ordinal":1,"at":[34.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Count Room Cam","streamRef":"rtsp://10.1.48.10/main"},
    {"id":"cam-1-49","ordinal":1,"at":[37.5,58.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Count Room Dome NW","streamRef":"rtsp://10.1.49.10/main"},
    {"id":"cam-1-50","ordinal":1,"at":[44.5,58.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Count Room Dome NE","streamRef":"rtsp://10.1.50.10/main"},
    {"id":"cam-1-51","ordinal":1,"at":[37.5,50.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Count Room Dome SW","streamRef":"rtsp://10.1.51.10/main"},
    {"id":"cam-1-52","ordinal":1,"at":[48.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Vault Cam","streamRef":"rtsp://10.1.52.10/main"},
    {"id":"cam-1-53","ordinal":1,"at":[58.5,58.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Vault Dome","streamRef":"rtsp://10.1.53.10/main"},
    {"id":"cam-1-54","ordinal":1,"at":[51.5,50.5],"heading":0,"fovDeg":360,"rangeM":12,"kind":"dome","name":"Vault Dome 2","streamRef":"rtsp://10.1.54.10/main"},
    {"id":"cam-1-55","ordinal":1,"at":[62.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Server Room Cam","streamRef":"rtsp://10.1.55.10/main"},
    {"id":"cam-1-56","ordinal":1,"at":[76.6,61.4],"heading":-47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Records Cam","streamRef":"rtsp://10.1.56.10/main"},
    {"id":"cam-1-57","ordinal":1,"at":[20.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Security Ops Cam","streamRef":"rtsp://10.1.57.10/main"},
    {"id":"cam-1-58","ordinal":1,"at":[34.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Surveillance Storage Cam","streamRef":"rtsp://10.1.58.10/main"},
    {"id":"cam-1-59","ordinal":1,"at":[48.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Executive Office Cam","streamRef":"rtsp://10.1.59.10/main"},
    {"id":"cam-1-60","ordinal":1,"at":[62.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Staff Break Room Cam","streamRef":"rtsp://10.1.60.10/main"},
    {"id":"cam-1-61","ordinal":1,"at":[76.6,28.6],"heading":47.15,"fovDeg":100,"rangeM":24.62,"kind":"fixed","name":"Receiving Cam","streamRef":"rtsp://10.1.61.10/main"},
    {"id":"cam-1-62","ordinal":1,"at":[30,45],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Service Corridor W","streamRef":"rtsp://10.1.62.10/main"},
    {"id":"cam-1-63","ordinal":1,"at":[55,45],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Service Corridor C","streamRef":"rtsp://10.1.63.10/main"},
    {"id":"cam-1-64","ordinal":1,"at":[80,45],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Service Corridor E","streamRef":"rtsp://10.1.64.10/main"},
    {"id":"cam-1-65","ordinal":1,"at":[93,50],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Stairwell Cam L1","streamRef":"rtsp://10.1.65.10/main"},
    {"id":"cam-1-66","ordinal":1,"at":[93,40],"heading":0,"fovDeg":360,"rangeM":6,"kind":"dome","name":"Elevator Cam L1","streamRef":"rtsp://10.1.66.10/main"},
  ],
  incidents: [
    {"id":"inc-1","ordinal":0,"at":[48.79,21.82],"kind":"theft","note":"Chip dispute flagged at Table Games."},
    {"id":"inc-2","ordinal":0,"at":[18,90],"kind":"alarm","note":"Cage drawer alarm 01:52."},
    {"id":"inc-3","ordinal":1,"at":[41,55],"kind":"trespass","note":"Unescorted contractor near Count Room."},
  ],
  patrols: [
    {"id":"patrol-0","ordinal":0,"name":"Floor Sweep","points":[[55,56.5],[55,45],[37.68,35],[45.42,18.69],[72.32,35]]},
    {"id":"patrol-1","ordinal":1,"name":"BOH Sweep","points":[[22,45],[55,45],[88,45]]},
  ],
};

/**
 * Units a user can pick as a route start/destination: every authored space
 * (room/office/restroom/lobby/retail/storage/mechanical/outside), excluding
 * circulation (corridor/elevator/stairs) and security-restricted units.
 */
export function selectableUnits(b: Building) {
  return b.units.filter((u) => isSpace(u.category) && !isNonRoutable(u));
}

/**
 * Place a door for a freshly-authored room: on the room's bounding-box edge
 * nearest the corridor, horizontally centred but clamped to the corridor's
 * extent. Good enough for the spike; doors become draggable next.
 */
export function doorForRoom(
  b: Building,
  polygon: MetreXY[],
  ordinal: number,
): MetreXY | null {
  const corridor = b.units.find((u) => u.category === "corridor" && u.ordinal === ordinal);
  if (!corridor) return null;
  const [cx0, cy0, cx1, cy1] = bbox(corridor.polygon);
  const [x0, y0, x1, y1] = bbox(polygon);
  const cx = Math.min(Math.max((x0 + x1) / 2, cx0), cx1);
  // Below the corridor band -> door on corridor's bottom edge; above -> top edge.
  if (y1 <= cy0) return [cx, cy0];
  if (y0 >= cy1) return [cx, cy1];
  return [cx, cy0];
}
