import type { Building, MetreXY } from "./types";
import { bbox } from "./geo";
import { isSpace, isNonRoutable } from "./categories";

// Demo "secure complex": 3 floors, two wings per floor flanking a central outdoor
// BREEZEWAY, each wing a double-loaded corridor of 6 rooms (36 rooms total). A
// stairwell (north) + elevator (south) link the floors; security escalates by
// floor (public lobby -> labs -> high-security vault/SCIF). Cameras follow standard
// placement (one per room + corridor ends + breezeway/core domes + redundant
// cameras in restricted rooms). Generated by scratch/_scratch-gen-demo.mjs.

/** Axis-aligned rectangle as a 4-vertex polygon (open ring). */
export function rectPoly(x0: number, y0: number, x1: number, y1: number): MetreXY[] {
  return [
    [x0, y0],
    [x1, y0],
    [x1, y1],
    [x0, y1],
  ];
}

/** A rectangle polygon from any two drag corners. */
export function rectFromDrag(a: MetreXY, b: MetreXY): MetreXY[] {
  return rectPoly(
    Math.min(a[0], b[0]),
    Math.min(a[1], b[1]),
    Math.max(a[0], b[0]),
    Math.max(a[1], b[1]),
  );
}

export const initialBuilding: Building = {
  origin: [-73.9857,40.7484],
  levels: [
    {"ordinal":0,"name":"Ground"},
    {"ordinal":1,"name":"Level 1 — Operations"},
    {"ordinal":2,"name":"Level 2 — Secure"},
  ],
  units: [
    {"id":"r-0-0","ordinal":0,"name":"Main Lobby","category":"room","polygon":[[0,0],[9,0],[9,22],[0,22]]},
    {"id":"r-0-3","ordinal":0,"name":"Waiting Area","category":"room","polygon":[[0,26],[9,26],[9,48],[0,48]]},
    {"id":"r-0-1","ordinal":0,"name":"Reception","category":"room","polygon":[[9,0],[18,0],[18,22],[9,22]]},
    {"id":"r-0-4","ordinal":0,"name":"Break Room","category":"room","polygon":[[9,26],[18,26],[18,48],[9,48]]},
    {"id":"r-0-2","ordinal":0,"name":"Visitor Screening","category":"room","polygon":[[18,0],[27,0],[27,22],[18,22]],"security":"secure"},
    {"id":"r-0-5","ordinal":0,"name":"Mailroom","category":"room","polygon":[[18,26],[27,26],[27,48],[18,48]]},
    {"id":"r-0-6","ordinal":0,"name":"Security Office","category":"room","polygon":[[37,0],[46,0],[46,22],[37,22]],"security":"secure"},
    {"id":"r-0-9","ordinal":0,"name":"Mechanical","category":"room","polygon":[[37,26],[46,26],[46,48],[37,48]],"security":"secure"},
    {"id":"r-0-7","ordinal":0,"name":"Guard Room","category":"room","polygon":[[46,0],[55,0],[55,22],[46,22]],"security":"restricted"},
    {"id":"r-0-10","ordinal":0,"name":"Comms Closet","category":"room","polygon":[[46,26],[55,26],[55,48],[46,48]],"security":"restricted"},
    {"id":"r-0-8","ordinal":0,"name":"Facilities","category":"room","polygon":[[55,0],[64,0],[64,22],[55,22]]},
    {"id":"r-0-11","ordinal":0,"name":"Loading Dock","category":"room","polygon":[[55,26],[64,26],[64,48],[55,48]],"security":"secure"},
    {"id":"cor-0-w","ordinal":0,"name":"West Corridor","category":"corridor","polygon":[[0,22],[27,22],[27,26],[0,26]]},
    {"id":"cor-0-e","ordinal":0,"name":"East Corridor","category":"corridor","polygon":[[37,22],[64,22],[64,26],[37,26]]},
    {"id":"brz-0","ordinal":0,"name":"Breezeway","category":"outside","polygon":[[27,6],[37,6],[37,42],[27,42]]},
    {"id":"stair-0","ordinal":0,"name":"Stairwell","category":"stairs","polygon":[[29,0],[35,0],[35,6],[29,6]]},
    {"id":"elev-0","ordinal":0,"name":"Elevator","category":"elevator","polygon":[[29,42],[35,42],[35,48],[29,48]]},
    {"id":"r-1-0","ordinal":1,"name":"Lab A","category":"room","polygon":[[0,0],[9,0],[9,22],[0,22]],"security":"secure"},
    {"id":"r-1-3","ordinal":1,"name":"Conference 1","category":"room","polygon":[[0,26],[9,26],[9,48],[0,48]]},
    {"id":"r-1-1","ordinal":1,"name":"Lab B","category":"room","polygon":[[9,0],[18,0],[18,22],[9,22]],"security":"secure"},
    {"id":"r-1-4","ordinal":1,"name":"Conference 2","category":"room","polygon":[[9,26],[18,26],[18,48],[9,48]]},
    {"id":"r-1-2","ordinal":1,"name":"Clean Room","category":"room","polygon":[[18,0],[27,0],[27,22],[18,22]],"security":"restricted"},
    {"id":"r-1-5","ordinal":1,"name":"Open Office","category":"room","polygon":[[18,26],[27,26],[27,48],[18,48]]},
    {"id":"r-1-6","ordinal":1,"name":"Server Room A","category":"room","polygon":[[37,0],[46,0],[46,22],[37,22]],"security":"restricted"},
    {"id":"r-1-9","ordinal":1,"name":"Records","category":"room","polygon":[[37,26],[46,26],[46,48],[37,48]],"security":"secure"},
    {"id":"r-1-7","ordinal":1,"name":"Server Room B","category":"room","polygon":[[46,0],[55,0],[55,22],[46,22]],"security":"restricted"},
    {"id":"r-1-10","ordinal":1,"name":"Storage","category":"room","polygon":[[46,26],[55,26],[55,48],[46,48]]},
    {"id":"r-1-8","ordinal":1,"name":"Network Ops","category":"room","polygon":[[55,0],[64,0],[64,22],[55,22]],"security":"secure"},
    {"id":"r-1-11","ordinal":1,"name":"Electrical","category":"room","polygon":[[55,26],[64,26],[64,48],[55,48]],"security":"secure"},
    {"id":"cor-1-w","ordinal":1,"name":"West Corridor","category":"corridor","polygon":[[0,22],[27,22],[27,26],[0,26]]},
    {"id":"cor-1-e","ordinal":1,"name":"East Corridor","category":"corridor","polygon":[[37,22],[64,22],[64,26],[37,26]]},
    {"id":"brz-1","ordinal":1,"name":"Sky Bridge","category":"outside","polygon":[[27,6],[37,6],[37,42],[27,42]]},
    {"id":"stair-1","ordinal":1,"name":"Stairwell","category":"stairs","polygon":[[29,0],[35,0],[35,6],[29,6]]},
    {"id":"elev-1","ordinal":1,"name":"Elevator","category":"elevator","polygon":[[29,42],[35,42],[35,48],[29,48]]},
    {"id":"r-2-0","ordinal":2,"name":"Data Vault","category":"room","polygon":[[0,0],[9,0],[9,22],[0,22]],"security":"restricted"},
    {"id":"r-2-3","ordinal":2,"name":"Command Center","category":"room","polygon":[[0,26],[9,26],[9,48],[0,48]],"security":"secure"},
    {"id":"r-2-1","ordinal":2,"name":"Control Room","category":"room","polygon":[[9,0],[18,0],[18,22],[9,22]],"security":"restricted"},
    {"id":"r-2-4","ordinal":2,"name":"Briefing Room","category":"room","polygon":[[9,26],[18,26],[18,48],[9,48]],"security":"secure"},
    {"id":"r-2-2","ordinal":2,"name":"SCIF","category":"room","polygon":[[18,0],[27,0],[27,22],[18,22]],"security":"restricted"},
    {"id":"r-2-5","ordinal":2,"name":"Executive Office","category":"room","polygon":[[18,26],[27,26],[27,48],[18,48]],"security":"secure"},
    {"id":"r-2-6","ordinal":2,"name":"Secure Archive","category":"room","polygon":[[37,0],[46,0],[46,22],[37,22]],"security":"restricted"},
    {"id":"r-2-9","ordinal":2,"name":"Monitoring","category":"room","polygon":[[37,26],[46,26],[46,48],[37,48]],"security":"secure"},
    {"id":"r-2-7","ordinal":2,"name":"Evidence Room","category":"room","polygon":[[46,0],[55,0],[55,22],[46,22]],"security":"restricted"},
    {"id":"r-2-10","ordinal":2,"name":"Secure Storage","category":"room","polygon":[[46,26],[55,26],[55,48],[46,48]],"security":"restricted"},
    {"id":"r-2-8","ordinal":2,"name":"Comms Center","category":"room","polygon":[[55,0],[64,0],[64,22],[55,22]],"security":"restricted"},
    {"id":"r-2-11","ordinal":2,"name":"Server Core","category":"room","polygon":[[55,26],[64,26],[64,48],[55,48]],"security":"restricted"},
    {"id":"cor-2-w","ordinal":2,"name":"West Corridor","category":"corridor","polygon":[[0,22],[27,22],[27,26],[0,26]]},
    {"id":"cor-2-e","ordinal":2,"name":"East Corridor","category":"corridor","polygon":[[37,22],[64,22],[64,26],[37,26]]},
    {"id":"brz-2","ordinal":2,"name":"Sky Bridge","category":"outside","polygon":[[27,6],[37,6],[37,42],[27,42]]},
    {"id":"stair-2","ordinal":2,"name":"Stairwell","category":"stairs","polygon":[[29,0],[35,0],[35,6],[29,6]]},
    {"id":"elev-2","ordinal":2,"name":"Elevator","category":"elevator","polygon":[[29,42],[35,42],[35,48],[29,48]]},
  ],
  openings: [
    {"id":"d-r-0-0","unit":"r-0-0","at":[4.5,22]},
    {"id":"d-r-0-3","unit":"r-0-3","at":[4.5,26]},
    {"id":"d-r-0-1","unit":"r-0-1","at":[13.5,22]},
    {"id":"d-r-0-4","unit":"r-0-4","at":[13.5,26]},
    {"id":"d-r-0-2","unit":"r-0-2","at":[22.5,22]},
    {"id":"d-r-0-5","unit":"r-0-5","at":[22.5,26]},
    {"id":"d-r-0-6","unit":"r-0-6","at":[41.5,22]},
    {"id":"d-r-0-9","unit":"r-0-9","at":[41.5,26]},
    {"id":"d-r-0-7","unit":"r-0-7","at":[50.5,22]},
    {"id":"d-r-0-10","unit":"r-0-10","at":[50.5,26]},
    {"id":"d-r-0-8","unit":"r-0-8","at":[59.5,22]},
    {"id":"d-r-0-11","unit":"r-0-11","at":[59.5,26]},
    {"id":"e-cor-0-w","unit":"cor-0-w","at":[27,24],"kind":"entrance"},
    {"id":"e-cor-0-e","unit":"cor-0-e","at":[37,24],"kind":"entrance"},
    {"id":"e-stair-0","unit":"stair-0","at":[32,6],"kind":"entrance"},
    {"id":"e-elev-0","unit":"elev-0","at":[32,42],"kind":"entrance"},
    {"id":"d-r-1-0","unit":"r-1-0","at":[4.5,22]},
    {"id":"d-r-1-3","unit":"r-1-3","at":[4.5,26]},
    {"id":"d-r-1-1","unit":"r-1-1","at":[13.5,22]},
    {"id":"d-r-1-4","unit":"r-1-4","at":[13.5,26]},
    {"id":"d-r-1-2","unit":"r-1-2","at":[22.5,22]},
    {"id":"d-r-1-5","unit":"r-1-5","at":[22.5,26]},
    {"id":"d-r-1-6","unit":"r-1-6","at":[41.5,22]},
    {"id":"d-r-1-9","unit":"r-1-9","at":[41.5,26]},
    {"id":"d-r-1-7","unit":"r-1-7","at":[50.5,22]},
    {"id":"d-r-1-10","unit":"r-1-10","at":[50.5,26]},
    {"id":"d-r-1-8","unit":"r-1-8","at":[59.5,22]},
    {"id":"d-r-1-11","unit":"r-1-11","at":[59.5,26]},
    {"id":"e-cor-1-w","unit":"cor-1-w","at":[27,24],"kind":"entrance"},
    {"id":"e-cor-1-e","unit":"cor-1-e","at":[37,24],"kind":"entrance"},
    {"id":"e-stair-1","unit":"stair-1","at":[32,6],"kind":"entrance"},
    {"id":"e-elev-1","unit":"elev-1","at":[32,42],"kind":"entrance"},
    {"id":"d-r-2-0","unit":"r-2-0","at":[4.5,22]},
    {"id":"d-r-2-3","unit":"r-2-3","at":[4.5,26]},
    {"id":"d-r-2-1","unit":"r-2-1","at":[13.5,22]},
    {"id":"d-r-2-4","unit":"r-2-4","at":[13.5,26]},
    {"id":"d-r-2-2","unit":"r-2-2","at":[22.5,22]},
    {"id":"d-r-2-5","unit":"r-2-5","at":[22.5,26]},
    {"id":"d-r-2-6","unit":"r-2-6","at":[41.5,22]},
    {"id":"d-r-2-9","unit":"r-2-9","at":[41.5,26]},
    {"id":"d-r-2-7","unit":"r-2-7","at":[50.5,22]},
    {"id":"d-r-2-10","unit":"r-2-10","at":[50.5,26]},
    {"id":"d-r-2-8","unit":"r-2-8","at":[59.5,22]},
    {"id":"d-r-2-11","unit":"r-2-11","at":[59.5,26]},
    {"id":"e-cor-2-w","unit":"cor-2-w","at":[27,24],"kind":"entrance"},
    {"id":"e-cor-2-e","unit":"cor-2-e","at":[37,24],"kind":"entrance"},
    {"id":"e-stair-2","unit":"stair-2","at":[32,6],"kind":"entrance"},
    {"id":"e-elev-2","unit":"elev-2","at":[32,42],"kind":"entrance"},
  ],
  verticals: [{"a":"stair-0","b":"stair-1","name":"Stairs"},{"a":"elev-0","b":"elev-1","name":"Elevator"},{"a":"stair-1","b":"stair-2","name":"Stairs"},{"a":"elev-1","b":"elev-2","name":"Elevator"}],
  cameras: [
    {"id":"cam-0-1","ordinal":0,"at":[0.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Main Lobby Cam","streamRef":"rtsp://10.0.1.10/main"},
    {"id":"cam-0-2","ordinal":0,"at":[0.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Waiting Area Cam","streamRef":"rtsp://10.0.2.10/main"},
    {"id":"cam-0-3","ordinal":0,"at":[9.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Reception Cam","streamRef":"rtsp://10.0.3.10/main"},
    {"id":"cam-0-4","ordinal":0,"at":[9.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Break Room Cam","streamRef":"rtsp://10.0.4.10/main"},
    {"id":"cam-0-5","ordinal":0,"at":[18.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Visitor Screening Cam","streamRef":"rtsp://10.0.5.10/main"},
    {"id":"cam-0-6","ordinal":0,"at":[18.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Mailroom Cam","streamRef":"rtsp://10.0.6.10/main"},
    {"id":"cam-0-7","ordinal":0,"at":[37.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Security Office Cam","streamRef":"rtsp://10.0.7.10/main"},
    {"id":"cam-0-8","ordinal":0,"at":[37.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Mechanical Cam","streamRef":"rtsp://10.0.8.10/main"},
    {"id":"cam-0-9","ordinal":0,"at":[46.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Guard Room Cam","streamRef":"rtsp://10.0.9.10/main"},
    {"id":"cam-0-10","ordinal":0,"at":[54.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Guard Room Cam 2","streamRef":"rtsp://10.0.10.10/main"},
    {"id":"cam-0-11","ordinal":0,"at":[46.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Comms Closet Cam","streamRef":"rtsp://10.0.11.10/main"},
    {"id":"cam-0-12","ordinal":0,"at":[54.4,47.4],"heading":-110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Comms Closet Cam 2","streamRef":"rtsp://10.0.12.10/main"},
    {"id":"cam-0-13","ordinal":0,"at":[55.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Facilities Cam","streamRef":"rtsp://10.0.13.10/main"},
    {"id":"cam-0-14","ordinal":0,"at":[55.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Loading Dock Cam","streamRef":"rtsp://10.0.14.10/main"},
    {"id":"cam-0-15","ordinal":0,"at":[1,24],"heading":0,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"West Corridor W","streamRef":"rtsp://10.0.15.10/main"},
    {"id":"cam-0-16","ordinal":0,"at":[26,24],"heading":180,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"West Corridor E","streamRef":"rtsp://10.0.16.10/main"},
    {"id":"cam-0-17","ordinal":0,"at":[38,24],"heading":0,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"East Corridor W","streamRef":"rtsp://10.0.17.10/main"},
    {"id":"cam-0-18","ordinal":0,"at":[63,24],"heading":180,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"East Corridor E","streamRef":"rtsp://10.0.18.10/main"},
    {"id":"cam-0-19","ordinal":0,"at":[32,15],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Breezeway North","streamRef":"rtsp://10.0.19.10/main"},
    {"id":"cam-0-20","ordinal":0,"at":[32,33],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Breezeway South","streamRef":"rtsp://10.0.20.10/main"},
    {"id":"cam-0-21","ordinal":0,"at":[30,1.5],"heading":0,"fovDeg":360,"rangeM":8,"kind":"dome","name":"Stairwell Cam","streamRef":"rtsp://10.0.21.10/main"},
    {"id":"cam-0-22","ordinal":0,"at":[30,46.5],"heading":0,"fovDeg":360,"rangeM":8,"kind":"dome","name":"Elevator Cam","streamRef":"rtsp://10.0.22.10/main"},
    {"id":"cam-1-23","ordinal":1,"at":[0.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Lab A Cam","streamRef":"rtsp://10.1.23.10/main"},
    {"id":"cam-1-24","ordinal":1,"at":[0.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Conference 1 Cam","streamRef":"rtsp://10.1.24.10/main"},
    {"id":"cam-1-25","ordinal":1,"at":[9.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Lab B Cam","streamRef":"rtsp://10.1.25.10/main"},
    {"id":"cam-1-26","ordinal":1,"at":[9.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Conference 2 Cam","streamRef":"rtsp://10.1.26.10/main"},
    {"id":"cam-1-27","ordinal":1,"at":[18.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Clean Room Cam","streamRef":"rtsp://10.1.27.10/main"},
    {"id":"cam-1-28","ordinal":1,"at":[26.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Clean Room Cam 2","streamRef":"rtsp://10.1.28.10/main"},
    {"id":"cam-1-29","ordinal":1,"at":[18.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Open Office Cam","streamRef":"rtsp://10.1.29.10/main"},
    {"id":"cam-1-30","ordinal":1,"at":[37.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Server Room A Cam","streamRef":"rtsp://10.1.30.10/main"},
    {"id":"cam-1-31","ordinal":1,"at":[45.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Server Room A Cam 2","streamRef":"rtsp://10.1.31.10/main"},
    {"id":"cam-1-32","ordinal":1,"at":[37.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Records Cam","streamRef":"rtsp://10.1.32.10/main"},
    {"id":"cam-1-33","ordinal":1,"at":[46.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Server Room B Cam","streamRef":"rtsp://10.1.33.10/main"},
    {"id":"cam-1-34","ordinal":1,"at":[54.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Server Room B Cam 2","streamRef":"rtsp://10.1.34.10/main"},
    {"id":"cam-1-35","ordinal":1,"at":[46.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Storage Cam","streamRef":"rtsp://10.1.35.10/main"},
    {"id":"cam-1-36","ordinal":1,"at":[55.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Network Ops Cam","streamRef":"rtsp://10.1.36.10/main"},
    {"id":"cam-1-37","ordinal":1,"at":[55.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Electrical Cam","streamRef":"rtsp://10.1.37.10/main"},
    {"id":"cam-1-38","ordinal":1,"at":[1,24],"heading":0,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"West Corridor W","streamRef":"rtsp://10.1.38.10/main"},
    {"id":"cam-1-39","ordinal":1,"at":[26,24],"heading":180,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"West Corridor E","streamRef":"rtsp://10.1.39.10/main"},
    {"id":"cam-1-40","ordinal":1,"at":[38,24],"heading":0,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"East Corridor W","streamRef":"rtsp://10.1.40.10/main"},
    {"id":"cam-1-41","ordinal":1,"at":[63,24],"heading":180,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"East Corridor E","streamRef":"rtsp://10.1.41.10/main"},
    {"id":"cam-1-42","ordinal":1,"at":[32,15],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Breezeway North","streamRef":"rtsp://10.1.42.10/main"},
    {"id":"cam-1-43","ordinal":1,"at":[32,33],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Breezeway South","streamRef":"rtsp://10.1.43.10/main"},
    {"id":"cam-1-44","ordinal":1,"at":[30,1.5],"heading":0,"fovDeg":360,"rangeM":8,"kind":"dome","name":"Stairwell Cam","streamRef":"rtsp://10.1.44.10/main"},
    {"id":"cam-1-45","ordinal":1,"at":[30,46.5],"heading":0,"fovDeg":360,"rangeM":8,"kind":"dome","name":"Elevator Cam","streamRef":"rtsp://10.1.45.10/main"},
    {"id":"cam-2-46","ordinal":2,"at":[0.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Data Vault Cam","streamRef":"rtsp://10.2.46.10/main"},
    {"id":"cam-2-47","ordinal":2,"at":[8.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Data Vault Cam 2","streamRef":"rtsp://10.2.47.10/main"},
    {"id":"cam-2-48","ordinal":2,"at":[0.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Command Center Cam","streamRef":"rtsp://10.2.48.10/main"},
    {"id":"cam-2-49","ordinal":2,"at":[9.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Control Room Cam","streamRef":"rtsp://10.2.49.10/main"},
    {"id":"cam-2-50","ordinal":2,"at":[17.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Control Room Cam 2","streamRef":"rtsp://10.2.50.10/main"},
    {"id":"cam-2-51","ordinal":2,"at":[9.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Briefing Room Cam","streamRef":"rtsp://10.2.51.10/main"},
    {"id":"cam-2-52","ordinal":2,"at":[18.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"SCIF Cam","streamRef":"rtsp://10.2.52.10/main"},
    {"id":"cam-2-53","ordinal":2,"at":[26.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"SCIF Cam 2","streamRef":"rtsp://10.2.53.10/main"},
    {"id":"cam-2-54","ordinal":2,"at":[18.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Executive Office Cam","streamRef":"rtsp://10.2.54.10/main"},
    {"id":"cam-2-55","ordinal":2,"at":[37.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Secure Archive Cam","streamRef":"rtsp://10.2.55.10/main"},
    {"id":"cam-2-56","ordinal":2,"at":[45.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Secure Archive Cam 2","streamRef":"rtsp://10.2.56.10/main"},
    {"id":"cam-2-57","ordinal":2,"at":[37.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Monitoring Cam","streamRef":"rtsp://10.2.57.10/main"},
    {"id":"cam-2-58","ordinal":2,"at":[46.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Evidence Room Cam","streamRef":"rtsp://10.2.58.10/main"},
    {"id":"cam-2-59","ordinal":2,"at":[54.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Evidence Room Cam 2","streamRef":"rtsp://10.2.59.10/main"},
    {"id":"cam-2-60","ordinal":2,"at":[46.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Secure Storage Cam","streamRef":"rtsp://10.2.60.10/main"},
    {"id":"cam-2-61","ordinal":2,"at":[54.4,47.4],"heading":-110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Secure Storage Cam 2","streamRef":"rtsp://10.2.61.10/main"},
    {"id":"cam-2-62","ordinal":2,"at":[55.6,21.4],"heading":-69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Comms Center Cam","streamRef":"rtsp://10.2.62.10/main"},
    {"id":"cam-2-63","ordinal":2,"at":[63.4,0.6],"heading":110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Comms Center Cam 2","streamRef":"rtsp://10.2.63.10/main"},
    {"id":"cam-2-64","ordinal":2,"at":[55.6,26.6],"heading":69.44,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Server Core Cam","streamRef":"rtsp://10.2.64.10/main"},
    {"id":"cam-2-65","ordinal":2,"at":[63.4,47.4],"heading":-110.56,"fovDeg":100,"rangeM":28.52,"kind":"fixed","name":"Server Core Cam 2","streamRef":"rtsp://10.2.65.10/main"},
    {"id":"cam-2-66","ordinal":2,"at":[1,24],"heading":0,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"West Corridor W","streamRef":"rtsp://10.2.66.10/main"},
    {"id":"cam-2-67","ordinal":2,"at":[26,24],"heading":180,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"West Corridor E","streamRef":"rtsp://10.2.67.10/main"},
    {"id":"cam-2-68","ordinal":2,"at":[38,24],"heading":0,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"East Corridor W","streamRef":"rtsp://10.2.68.10/main"},
    {"id":"cam-2-69","ordinal":2,"at":[63,24],"heading":180,"fovDeg":60,"rangeM":30,"kind":"fixed","name":"East Corridor E","streamRef":"rtsp://10.2.69.10/main"},
    {"id":"cam-2-70","ordinal":2,"at":[32,15],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Breezeway North","streamRef":"rtsp://10.2.70.10/main"},
    {"id":"cam-2-71","ordinal":2,"at":[32,33],"heading":0,"fovDeg":360,"rangeM":14,"kind":"dome","name":"Breezeway South","streamRef":"rtsp://10.2.71.10/main"},
    {"id":"cam-2-72","ordinal":2,"at":[30,1.5],"heading":0,"fovDeg":360,"rangeM":8,"kind":"dome","name":"Stairwell Cam","streamRef":"rtsp://10.2.72.10/main"},
    {"id":"cam-2-73","ordinal":2,"at":[30,46.5],"heading":0,"fovDeg":360,"rangeM":8,"kind":"dome","name":"Elevator Cam","streamRef":"rtsp://10.2.73.10/main"},
  ],
  incidents: [
    {"id":"inc-1","ordinal":0,"at":[6,10],"kind":"medical","note":"Visitor collapse near reception."},
    {"id":"inc-2","ordinal":0,"at":[4,34],"kind":"hazard","note":"Coolant leak flagged in Mechanical."},
    {"id":"inc-3","ordinal":2,"at":[4.5,11],"kind":"alarm","note":"Data Vault door forced 02:14."},
    {"id":"inc-4","ordinal":2,"at":[50,24],"kind":"trespass","note":"Unbadged individual in east corridor."},
  ],
  patrols: [
    {"id":"patrol-0","ordinal":0,"name":"Ground Perimeter Sweep","points":[[2,24],[26,24],[32,24],[38,24],[63,24]]},
    {"id":"patrol-1","ordinal":1,"name":"Level Perimeter Sweep","points":[[2,24],[26,24],[32,24],[38,24],[63,24]]},
    {"id":"patrol-2","ordinal":2,"name":"Level Perimeter Sweep","points":[[2,24],[26,24],[32,24],[38,24],[63,24]]},
  ],
};

/**
 * Units a user can pick as a route start/destination: every authored space
 * (room/office/restroom/lobby/retail/storage/mechanical/outside), excluding
 * circulation (corridor/elevator/stairs) and security-restricted units.
 */
export function selectableUnits(b: Building) {
  return b.units.filter((u) => isSpace(u.category) && !isNonRoutable(u));
}

/**
 * Place a door for a freshly-authored room: on the room's bounding-box edge
 * nearest the corridor, horizontally centred but clamped to the corridor's
 * extent. Good enough for the spike; doors become draggable next.
 */
export function doorForRoom(
  b: Building,
  polygon: MetreXY[],
  ordinal: number,
): MetreXY | null {
  const corridor = b.units.find((u) => u.category === "corridor" && u.ordinal === ordinal);
  if (!corridor) return null;
  const [cx0, cy0, cx1, cy1] = bbox(corridor.polygon);
  const [x0, y0, x1, y1] = bbox(polygon);
  const cx = Math.min(Math.max((x0 + x1) / 2, cx0), cx1);
  // Below the corridor band -> door on corridor's bottom edge; above -> top edge.
  if (y1 <= cy0) return [cx, cy0];
  if (y0 >= cy1) return [cx, cy1];
  return [cx, cy0];
}
