import type { Building } from "../types";
// Demo property: The Paramount — generator-built 2-floor large music venue.
// Program L0 (Ground — Hall & BOH): exterior Queue Canopy (outside) in front of
// the Screening Vestibule (bag-check choke); Box Office + Will Call flank it;
// 2 Merch Stands bookend the front strip; Coat Check. Front Corridor (the
// floor's sole routing hub) runs the full width behind the front strip. Main
// Hall (with a GA Pit fixture band before the stage + a walled FOH Mix Booth
// island mid-hall) is flanked by Bar 1/Bar 2/Backbar Storage (west) and Bar 3
// (east), with Stair A (west) and Elevator + Stair B (east) rising from the
// hall margins. Stage + Stage Left/Right Wings + Monitor World back the hall.
// A rear BOH wing (2 rows x 5 cols, matching the casino's wing convention)
// holds Greenroom 1-3 + Star Dressing Room + Ramp Corridor (row 1, adjoining
// the stage wings) and Production Office + Catering Kitchen + Cash Room
// (restricted) + Staff Break Room + Load-in Dock (row 2). Smoking Patio
// (outside) sits behind Staff Break Room.
// Program L1 (Mezzanine & VIP Boxes): 6 VIP Boxes (secure) + Mezzanine Bar
// along the front, Mezzanine Concourse (the floor's routing hub) behind them,
// then a U-shaped balcony (Mezzanine West/East, with Stair A/Elevator/Stair B
// carved into the wings) overlooking the open hall below — the open well
// (Main Hall's void) is excluded from the L1 footprint, keyhole-style, same
// technique as the stadium's upper deck.
// Verticals: Stair A + Stair B + Elevator link L0<->L1.
// Patrols: "Hall & Bars Loop" (L0, through the hall + all 3 bars), "Mezzanine
// Loop" (L1, around the U).
// Plant via scratch/_scratch-plant-lib planPlant: chokeZones = Screening
// Vestibule + Box Office + Cash Room + Load-in Dock + Stage; domeZones = Cash
// Room; targetSingle 0.87, targetMulti 0.75, fillCap 100. Corner-mount pass
// has no dedupe guard (constraint 4) — post-filtered for near-duplicate pairs
// (<=1.5m & <=25deg, same floor) before emission.
//
// planPlant report:
// ord0: corners 98, fill 3, multi 3 -> 104 cams | single 88%, >=2 76%
// ord1: corners 32, fill 0, multi 0 -> 32 cams | single 89%, >=2 84%
//
// Generated by scratch/_scratch-gen-venue-large.test.ts.
export const venueLargeBuilding: Building = {
  "origin": [
    -114.8728,
    36.1147
  ],
  "levels": [
    {
      "ordinal": 0,
      "name": "Ground — Hall & BOH",
      "ceilingM": 9
    },
    {
      "ordinal": 1,
      "name": "Mezzanine & VIP Boxes",
      "ceilingM": 4.5
    }
  ],
  "units": [
    {
      "id": "merch1-0",
      "ordinal": 0,
      "name": "Merch Stand 1",
      "category": "retail",
      "polygon": [
        [
          0,
          0
        ],
        [
          18,
          0
        ],
        [
          18,
          16
        ],
        [
          0,
          16
        ]
      ]
    },
    {
      "id": "boxoffice-0",
      "ordinal": 0,
      "name": "Box Office",
      "category": "office",
      "polygon": [
        [
          18,
          0
        ],
        [
          40,
          0
        ],
        [
          40,
          16
        ],
        [
          18,
          16
        ]
      ]
    },
    {
      "id": "willcall-0",
      "ordinal": 0,
      "name": "Will Call",
      "category": "office",
      "polygon": [
        [
          40,
          0
        ],
        [
          55,
          0
        ],
        [
          55,
          16
        ],
        [
          40,
          16
        ]
      ]
    },
    {
      "id": "vestibule-0",
      "ordinal": 0,
      "name": "Screening Vestibule",
      "category": "lobby",
      "polygon": [
        [
          55,
          0
        ],
        [
          95,
          0
        ],
        [
          95,
          16
        ],
        [
          55,
          16
        ]
      ]
    },
    {
      "id": "coatcheck-0",
      "ordinal": 0,
      "name": "Coat Check",
      "category": "storage",
      "polygon": [
        [
          95,
          0
        ],
        [
          115,
          0
        ],
        [
          115,
          16
        ],
        [
          95,
          16
        ]
      ]
    },
    {
      "id": "merch2-0",
      "ordinal": 0,
      "name": "Merch Stand 2",
      "category": "retail",
      "polygon": [
        [
          115,
          0
        ],
        [
          140,
          0
        ],
        [
          140,
          16
        ],
        [
          115,
          16
        ]
      ]
    },
    {
      "id": "frontcorridor-0",
      "ordinal": 0,
      "name": "Front Corridor",
      "category": "corridor",
      "polygon": [
        [
          0,
          16
        ],
        [
          140,
          16
        ],
        [
          140,
          24
        ],
        [
          0,
          24
        ]
      ]
    },
    {
      "id": "stair-a-0",
      "ordinal": 0,
      "name": "Stair A",
      "category": "stairs",
      "polygon": [
        [
          0,
          24
        ],
        [
          15,
          24
        ],
        [
          15,
          34
        ],
        [
          0,
          34
        ]
      ]
    },
    {
      "id": "bar1-0",
      "ordinal": 0,
      "name": "Bar 1",
      "category": "room",
      "polygon": [
        [
          0,
          34
        ],
        [
          15,
          34
        ],
        [
          15,
          50
        ],
        [
          0,
          50
        ]
      ]
    },
    {
      "id": "bar2-0",
      "ordinal": 0,
      "name": "Bar 2",
      "category": "room",
      "polygon": [
        [
          0,
          50
        ],
        [
          15,
          50
        ],
        [
          15,
          66
        ],
        [
          0,
          66
        ]
      ]
    },
    {
      "id": "backbar-0",
      "ordinal": 0,
      "name": "Backbar Storage",
      "category": "storage",
      "polygon": [
        [
          0,
          66
        ],
        [
          15,
          66
        ],
        [
          15,
          76
        ],
        [
          0,
          76
        ]
      ]
    },
    {
      "id": "hall-0",
      "ordinal": 0,
      "name": "Main Hall",
      "category": "room",
      "polygon": [
        [
          15,
          24
        ],
        [
          125,
          24
        ],
        [
          125,
          76
        ],
        [
          15,
          76
        ]
      ]
    },
    {
      "id": "foh-0",
      "ordinal": 0,
      "name": "FOH Mix Booth",
      "category": "room",
      "polygon": [
        [
          64,
          38
        ],
        [
          76,
          38
        ],
        [
          76,
          46
        ],
        [
          64,
          46
        ]
      ]
    },
    {
      "id": "bar3-0",
      "ordinal": 0,
      "name": "Bar 3",
      "category": "room",
      "polygon": [
        [
          125,
          24
        ],
        [
          140,
          24
        ],
        [
          140,
          56
        ],
        [
          125,
          56
        ]
      ]
    },
    {
      "id": "elevator-0",
      "ordinal": 0,
      "name": "Elevator",
      "category": "elevator",
      "polygon": [
        [
          125,
          56
        ],
        [
          140,
          56
        ],
        [
          140,
          66
        ],
        [
          125,
          66
        ]
      ]
    },
    {
      "id": "stair-b-0",
      "ordinal": 0,
      "name": "Stair B",
      "category": "stairs",
      "polygon": [
        [
          125,
          66
        ],
        [
          140,
          66
        ],
        [
          140,
          76
        ],
        [
          125,
          76
        ]
      ]
    },
    {
      "id": "stageleft-0",
      "ordinal": 0,
      "name": "Stage Left Wing",
      "category": "room",
      "polygon": [
        [
          0,
          76
        ],
        [
          25,
          76
        ],
        [
          25,
          100
        ],
        [
          0,
          100
        ]
      ]
    },
    {
      "id": "stage-0",
      "ordinal": 0,
      "name": "Stage",
      "category": "room",
      "polygon": [
        [
          25,
          76
        ],
        [
          115,
          76
        ],
        [
          115,
          100
        ],
        [
          25,
          100
        ]
      ]
    },
    {
      "id": "stageright-0",
      "ordinal": 0,
      "name": "Stage Right Wing",
      "category": "room",
      "polygon": [
        [
          115,
          76
        ],
        [
          140,
          76
        ],
        [
          140,
          90
        ],
        [
          115,
          90
        ]
      ]
    },
    {
      "id": "monitorworld-0",
      "ordinal": 0,
      "name": "Monitor World",
      "category": "room",
      "polygon": [
        [
          115,
          90
        ],
        [
          140,
          90
        ],
        [
          140,
          100
        ],
        [
          115,
          100
        ]
      ]
    },
    {
      "id": "greenroom1-0",
      "ordinal": 0,
      "name": "Greenroom 1",
      "category": "room",
      "polygon": [
        [
          15,
          100
        ],
        [
          40,
          100
        ],
        [
          40,
          125
        ],
        [
          15,
          125
        ]
      ]
    },
    {
      "id": "greenroom2-0",
      "ordinal": 0,
      "name": "Greenroom 2",
      "category": "room",
      "polygon": [
        [
          40,
          100
        ],
        [
          65,
          100
        ],
        [
          65,
          125
        ],
        [
          40,
          125
        ]
      ]
    },
    {
      "id": "greenroom3-0",
      "ordinal": 0,
      "name": "Greenroom 3",
      "category": "room",
      "polygon": [
        [
          65,
          100
        ],
        [
          90,
          100
        ],
        [
          90,
          125
        ],
        [
          65,
          125
        ]
      ]
    },
    {
      "id": "stardressing-0",
      "ordinal": 0,
      "name": "Star Dressing Room",
      "category": "room",
      "polygon": [
        [
          90,
          100
        ],
        [
          115,
          100
        ],
        [
          115,
          125
        ],
        [
          90,
          125
        ]
      ]
    },
    {
      "id": "rampcorridor-0",
      "ordinal": 0,
      "name": "Ramp Corridor",
      "category": "corridor",
      "polygon": [
        [
          115,
          100
        ],
        [
          140,
          100
        ],
        [
          140,
          125
        ],
        [
          115,
          125
        ]
      ]
    },
    {
      "id": "prodoffice-0",
      "ordinal": 0,
      "name": "Production Office",
      "category": "office",
      "polygon": [
        [
          15,
          125
        ],
        [
          40,
          125
        ],
        [
          40,
          150
        ],
        [
          15,
          150
        ]
      ]
    },
    {
      "id": "kitchen-0",
      "ordinal": 0,
      "name": "Catering Kitchen",
      "category": "storage",
      "polygon": [
        [
          40,
          125
        ],
        [
          65,
          125
        ],
        [
          65,
          150
        ],
        [
          40,
          150
        ]
      ]
    },
    {
      "id": "cashroom-0",
      "ordinal": 0,
      "name": "Cash Room",
      "category": "room",
      "security": "restricted",
      "polygon": [
        [
          65,
          125
        ],
        [
          90,
          125
        ],
        [
          90,
          150
        ],
        [
          65,
          150
        ]
      ]
    },
    {
      "id": "staffbreak-0",
      "ordinal": 0,
      "name": "Staff Break Room",
      "category": "room",
      "polygon": [
        [
          90,
          125
        ],
        [
          115,
          125
        ],
        [
          115,
          150
        ],
        [
          90,
          150
        ]
      ]
    },
    {
      "id": "loaddock-0",
      "ordinal": 0,
      "name": "Load-in Dock",
      "category": "storage",
      "polygon": [
        [
          115,
          125
        ],
        [
          140,
          125
        ],
        [
          140,
          150
        ],
        [
          115,
          150
        ]
      ]
    },
    {
      "id": "canopy-0",
      "ordinal": 0,
      "name": "Queue Canopy",
      "category": "outside",
      "polygon": [
        [
          50,
          -20
        ],
        [
          100,
          -20
        ],
        [
          100,
          0
        ],
        [
          50,
          0
        ]
      ]
    },
    {
      "id": "patio-0",
      "ordinal": 0,
      "name": "Smoking Patio",
      "category": "outside",
      "polygon": [
        [
          90,
          150
        ],
        [
          115,
          150
        ],
        [
          115,
          170
        ],
        [
          90,
          170
        ]
      ]
    },
    {
      "id": "vipbox1-1",
      "ordinal": 1,
      "name": "VIP Box 1",
      "category": "room",
      "security": "secure",
      "polygon": [
        [
          15,
          0
        ],
        [
          30,
          0
        ],
        [
          30,
          24
        ],
        [
          15,
          24
        ]
      ]
    },
    {
      "id": "vipbox2-1",
      "ordinal": 1,
      "name": "VIP Box 2",
      "category": "room",
      "security": "secure",
      "polygon": [
        [
          30,
          0
        ],
        [
          45,
          0
        ],
        [
          45,
          24
        ],
        [
          30,
          24
        ]
      ]
    },
    {
      "id": "vipbox3-1",
      "ordinal": 1,
      "name": "VIP Box 3",
      "category": "room",
      "security": "secure",
      "polygon": [
        [
          45,
          0
        ],
        [
          60,
          0
        ],
        [
          60,
          24
        ],
        [
          45,
          24
        ]
      ]
    },
    {
      "id": "vipbox4-1",
      "ordinal": 1,
      "name": "VIP Box 4",
      "category": "room",
      "security": "secure",
      "polygon": [
        [
          60,
          0
        ],
        [
          75,
          0
        ],
        [
          75,
          24
        ],
        [
          60,
          24
        ]
      ]
    },
    {
      "id": "vipbox5-1",
      "ordinal": 1,
      "name": "VIP Box 5",
      "category": "room",
      "security": "secure",
      "polygon": [
        [
          75,
          0
        ],
        [
          90,
          0
        ],
        [
          90,
          24
        ],
        [
          75,
          24
        ]
      ]
    },
    {
      "id": "vipbox6-1",
      "ordinal": 1,
      "name": "VIP Box 6",
      "category": "room",
      "security": "secure",
      "polygon": [
        [
          90,
          0
        ],
        [
          105,
          0
        ],
        [
          105,
          24
        ],
        [
          90,
          24
        ]
      ]
    },
    {
      "id": "mezzbar-1",
      "ordinal": 1,
      "name": "Mezzanine Bar",
      "category": "room",
      "polygon": [
        [
          105,
          0
        ],
        [
          125,
          0
        ],
        [
          125,
          24
        ],
        [
          105,
          24
        ]
      ]
    },
    {
      "id": "mezzconcourse-1",
      "ordinal": 1,
      "name": "Mezzanine Concourse",
      "category": "corridor",
      "polygon": [
        [
          15,
          24
        ],
        [
          125,
          24
        ],
        [
          125,
          40
        ],
        [
          15,
          40
        ]
      ]
    },
    {
      "id": "stair-a-1",
      "ordinal": 1,
      "name": "Stair A",
      "category": "stairs",
      "polygon": [
        [
          15,
          40
        ],
        [
          30,
          40
        ],
        [
          30,
          50
        ],
        [
          15,
          50
        ]
      ]
    },
    {
      "id": "mezzwest-1",
      "ordinal": 1,
      "name": "Mezzanine West",
      "category": "room",
      "polygon": [
        [
          15,
          50
        ],
        [
          30,
          50
        ],
        [
          30,
          76
        ],
        [
          15,
          76
        ]
      ]
    },
    {
      "id": "elevator-1",
      "ordinal": 1,
      "name": "Elevator",
      "category": "elevator",
      "polygon": [
        [
          110,
          40
        ],
        [
          125,
          40
        ],
        [
          125,
          50
        ],
        [
          110,
          50
        ]
      ]
    },
    {
      "id": "stair-b-1",
      "ordinal": 1,
      "name": "Stair B",
      "category": "stairs",
      "polygon": [
        [
          110,
          50
        ],
        [
          125,
          50
        ],
        [
          125,
          60
        ],
        [
          110,
          60
        ]
      ]
    },
    {
      "id": "mezzeast-1",
      "ordinal": 1,
      "name": "Mezzanine East",
      "category": "room",
      "polygon": [
        [
          110,
          60
        ],
        [
          125,
          60
        ],
        [
          125,
          76
        ],
        [
          110,
          76
        ]
      ]
    }
  ],
  "openings": [
    {
      "id": "d-1",
      "unit": "merch1-0",
      "at": [
        9,
        16
      ]
    },
    {
      "id": "d-2",
      "unit": "boxoffice-0",
      "at": [
        29,
        16
      ]
    },
    {
      "id": "d-3",
      "unit": "willcall-0",
      "at": [
        47,
        16
      ]
    },
    {
      "id": "d-4",
      "unit": "vestibule-0",
      "at": [
        75,
        0
      ],
      "kind": "entrance"
    },
    {
      "id": "d-5",
      "unit": "vestibule-0",
      "at": [
        75,
        16
      ]
    },
    {
      "id": "d-6",
      "unit": "coatcheck-0",
      "at": [
        105,
        16
      ]
    },
    {
      "id": "d-7",
      "unit": "merch2-0",
      "at": [
        127,
        16
      ]
    },
    {
      "id": "d-8",
      "unit": "stair-a-0",
      "at": [
        7,
        24
      ]
    },
    {
      "id": "d-9",
      "unit": "bar1-0",
      "at": [
        15,
        42
      ]
    },
    {
      "id": "d-10",
      "unit": "bar2-0",
      "at": [
        15,
        58
      ]
    },
    {
      "id": "d-11",
      "unit": "backbar-0",
      "at": [
        15,
        71
      ]
    },
    {
      "id": "d-12",
      "unit": "hall-0",
      "at": [
        70,
        24
      ]
    },
    {
      "id": "d-13",
      "unit": "foh-0",
      "at": [
        70,
        38
      ]
    },
    {
      "id": "d-14",
      "unit": "bar3-0",
      "at": [
        125,
        40
      ]
    },
    {
      "id": "d-15",
      "unit": "elevator-0",
      "at": [
        125,
        61
      ]
    },
    {
      "id": "d-16",
      "unit": "stair-b-0",
      "at": [
        125,
        71
      ]
    },
    {
      "id": "d-17",
      "unit": "stageleft-0",
      "at": [
        20,
        76
      ]
    },
    {
      "id": "d-18",
      "unit": "stage-0",
      "at": [
        70,
        76
      ]
    },
    {
      "id": "d-19",
      "unit": "stageright-0",
      "at": [
        120,
        76
      ]
    },
    {
      "id": "d-20",
      "unit": "monitorworld-0",
      "at": [
        127,
        90
      ]
    },
    {
      "id": "d-21",
      "unit": "greenroom1-0",
      "at": [
        20,
        100
      ]
    },
    {
      "id": "d-22",
      "unit": "greenroom2-0",
      "at": [
        52,
        100
      ]
    },
    {
      "id": "d-23",
      "unit": "greenroom3-0",
      "at": [
        77,
        100
      ]
    },
    {
      "id": "d-24",
      "unit": "stardressing-0",
      "at": [
        102,
        100
      ]
    },
    {
      "id": "d-25",
      "unit": "rampcorridor-0",
      "at": [
        127,
        100
      ]
    },
    {
      "id": "d-26",
      "unit": "prodoffice-0",
      "at": [
        27,
        125
      ]
    },
    {
      "id": "d-27",
      "unit": "kitchen-0",
      "at": [
        52,
        125
      ]
    },
    {
      "id": "d-28",
      "unit": "cashroom-0",
      "at": [
        77,
        125
      ]
    },
    {
      "id": "d-29",
      "unit": "staffbreak-0",
      "at": [
        102,
        125
      ]
    },
    {
      "id": "d-30",
      "unit": "staffbreak-0",
      "at": [
        102,
        150
      ],
      "kind": "entrance"
    },
    {
      "id": "d-31",
      "unit": "loaddock-0",
      "at": [
        127,
        125
      ]
    },
    {
      "id": "d-32",
      "unit": "loaddock-0",
      "at": [
        127,
        150
      ],
      "kind": "entrance"
    },
    {
      "id": "d-33",
      "unit": "vipbox1-1",
      "at": [
        22,
        24
      ]
    },
    {
      "id": "d-34",
      "unit": "vipbox2-1",
      "at": [
        37,
        24
      ]
    },
    {
      "id": "d-35",
      "unit": "vipbox3-1",
      "at": [
        52,
        24
      ]
    },
    {
      "id": "d-36",
      "unit": "vipbox4-1",
      "at": [
        67,
        24
      ]
    },
    {
      "id": "d-37",
      "unit": "vipbox5-1",
      "at": [
        82,
        24
      ]
    },
    {
      "id": "d-38",
      "unit": "vipbox6-1",
      "at": [
        97,
        24
      ]
    },
    {
      "id": "d-39",
      "unit": "mezzbar-1",
      "at": [
        115,
        24
      ]
    },
    {
      "id": "d-40",
      "unit": "stair-a-1",
      "at": [
        22,
        40
      ]
    },
    {
      "id": "d-41",
      "unit": "mezzwest-1",
      "at": [
        22,
        50
      ]
    },
    {
      "id": "d-42",
      "unit": "elevator-1",
      "at": [
        117,
        40
      ]
    },
    {
      "id": "d-43",
      "unit": "stair-b-1",
      "at": [
        117,
        50
      ]
    },
    {
      "id": "d-44",
      "unit": "mezzeast-1",
      "at": [
        117,
        60
      ]
    }
  ],
  "verticals": [
    {
      "a": "stair-a-0",
      "b": "stair-a-1",
      "name": "Stair A"
    },
    {
      "a": "stair-b-0",
      "b": "stair-b-1",
      "name": "Stair B"
    },
    {
      "a": "elevator-0",
      "b": "elevator-1",
      "name": "Elevator"
    }
  ],
  "cameras": [
    {
      "id": "cam-0-p1",
      "ordinal": 0,
      "at": [
        1,
        0.9
      ],
      "heading": 42,
      "fovDeg": 100,
      "rangeM": 29,
      "kind": "ptz",
      "name": "Merch Stand 1 · PTZ 01",
      "streamRef": "rtsp://10.1.50.1/main"
    },
    {
      "id": "cam-0-p2",
      "ordinal": 0,
      "at": [
        17,
        0.9
      ],
      "heading": 138,
      "fovDeg": 100,
      "rangeM": 29,
      "kind": "ptz",
      "name": "Merch Stand 1 · PTZ 02",
      "streamRef": "rtsp://10.1.50.2/main"
    },
    {
      "id": "cam-0-p3",
      "ordinal": 0,
      "at": [
        17,
        15.1
      ],
      "heading": 222,
      "fovDeg": 100,
      "rangeM": 29,
      "kind": "ptz",
      "name": "Merch Stand 1 · PTZ 03",
      "streamRef": "rtsp://10.1.50.3/main"
    },
    {
      "id": "cam-0-p4",
      "ordinal": 0,
      "at": [
        19.1,
        0.8
      ],
      "heading": 36,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Box Office · PTZ 04",
      "streamRef": "rtsp://10.1.50.4/main"
    },
    {
      "id": "cam-0-p5",
      "ordinal": 0,
      "at": [
        38.9,
        0.8
      ],
      "heading": 144,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Box Office · PTZ 05",
      "streamRef": "rtsp://10.1.50.5/main"
    },
    {
      "id": "cam-0-p6",
      "ordinal": 0,
      "at": [
        38.9,
        15.2
      ],
      "heading": 216,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Box Office · PTZ 06",
      "streamRef": "rtsp://10.1.50.6/main"
    },
    {
      "id": "cam-0-p7",
      "ordinal": 0,
      "at": [
        19.1,
        15.2
      ],
      "heading": 324,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Box Office · PTZ 07",
      "streamRef": "rtsp://10.1.50.7/main"
    },
    {
      "id": "cam-0-p8",
      "ordinal": 0,
      "at": [
        40.9,
        0.9
      ],
      "heading": 47,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Will Call · PTZ 08",
      "streamRef": "rtsp://10.1.50.8/main"
    },
    {
      "id": "cam-0-p9",
      "ordinal": 0,
      "at": [
        54.1,
        0.9
      ],
      "heading": 133,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Will Call · PTZ 09",
      "streamRef": "rtsp://10.1.50.9/main"
    },
    {
      "id": "cam-0-p10",
      "ordinal": 0,
      "at": [
        54.1,
        15.1
      ],
      "heading": 227,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Will Call · PTZ 10",
      "streamRef": "rtsp://10.1.50.10/main"
    },
    {
      "id": "cam-0-p11",
      "ordinal": 0,
      "at": [
        56.2,
        0.5
      ],
      "heading": 22,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Screening Vestibule · PTZ 11",
      "streamRef": "rtsp://10.1.50.11/main"
    },
    {
      "id": "cam-0-p12",
      "ordinal": 0,
      "at": [
        93.8,
        0.5
      ],
      "heading": 158,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Screening Vestibule · PTZ 12",
      "streamRef": "rtsp://10.1.50.12/main"
    },
    {
      "id": "cam-0-p13",
      "ordinal": 0,
      "at": [
        93.8,
        15.5
      ],
      "heading": 202,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Screening Vestibule · PTZ 13",
      "streamRef": "rtsp://10.1.50.13/main"
    },
    {
      "id": "cam-0-p14",
      "ordinal": 0,
      "at": [
        56.2,
        15.5
      ],
      "heading": 338,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Screening Vestibule · PTZ 14",
      "streamRef": "rtsp://10.1.50.14/main"
    },
    {
      "id": "cam-0-p15",
      "ordinal": 0,
      "at": [
        96,
        0.8
      ],
      "heading": 39,
      "fovDeg": 100,
      "rangeM": 30,
      "kind": "ptz",
      "name": "Coat Check · PTZ 15",
      "streamRef": "rtsp://10.1.50.15/main"
    },
    {
      "id": "cam-0-p16",
      "ordinal": 0,
      "at": [
        114,
        0.8
      ],
      "heading": 141,
      "fovDeg": 100,
      "rangeM": 30,
      "kind": "ptz",
      "name": "Coat Check · PTZ 16",
      "streamRef": "rtsp://10.1.50.16/main"
    },
    {
      "id": "cam-0-p17",
      "ordinal": 0,
      "at": [
        114,
        15.2
      ],
      "heading": 219,
      "fovDeg": 100,
      "rangeM": 30,
      "kind": "ptz",
      "name": "Coat Check · PTZ 17",
      "streamRef": "rtsp://10.1.50.17/main"
    },
    {
      "id": "cam-0-p18",
      "ordinal": 0,
      "at": [
        116.1,
        0.7
      ],
      "heading": 33,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Merch Stand 2 · PTZ 18",
      "streamRef": "rtsp://10.1.50.18/main"
    },
    {
      "id": "cam-0-p19",
      "ordinal": 0,
      "at": [
        138.9,
        0.7
      ],
      "heading": 147,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Merch Stand 2 · PTZ 19",
      "streamRef": "rtsp://10.1.50.19/main"
    },
    {
      "id": "cam-0-p20",
      "ordinal": 0,
      "at": [
        138.9,
        15.3
      ],
      "heading": 213,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Merch Stand 2 · PTZ 20",
      "streamRef": "rtsp://10.1.50.20/main"
    },
    {
      "id": "cam-0-p21",
      "ordinal": 0,
      "at": [
        116.1,
        15.3
      ],
      "heading": 327,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Merch Stand 2 · PTZ 21",
      "streamRef": "rtsp://10.1.50.21/main"
    },
    {
      "id": "cam-0-p22",
      "ordinal": 0,
      "at": [
        1.3,
        16.1
      ],
      "heading": 3,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Front Corridor · PTZ 22",
      "streamRef": "rtsp://10.1.50.22/main"
    },
    {
      "id": "cam-0-p23",
      "ordinal": 0,
      "at": [
        138.7,
        16.1
      ],
      "heading": 177,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Front Corridor · PTZ 23",
      "streamRef": "rtsp://10.1.50.23/main"
    },
    {
      "id": "cam-0-p24",
      "ordinal": 0,
      "at": [
        138.7,
        23.9
      ],
      "heading": 183,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Front Corridor · PTZ 24",
      "streamRef": "rtsp://10.1.50.24/main"
    },
    {
      "id": "cam-0-p25",
      "ordinal": 0,
      "at": [
        1.3,
        23.9
      ],
      "heading": 357,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Front Corridor · PTZ 25",
      "streamRef": "rtsp://10.1.50.25/main"
    },
    {
      "id": "cam-0-p26",
      "ordinal": 0,
      "at": [
        0.9,
        34.9
      ],
      "heading": 47,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Bar 1 · PTZ 26",
      "streamRef": "rtsp://10.1.50.26/main"
    },
    {
      "id": "cam-0-p27",
      "ordinal": 0,
      "at": [
        14.1,
        34.9
      ],
      "heading": 133,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Bar 1 · PTZ 27",
      "streamRef": "rtsp://10.1.50.27/main"
    },
    {
      "id": "cam-0-p28",
      "ordinal": 0,
      "at": [
        14.1,
        49.1
      ],
      "heading": 227,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Bar 1 · PTZ 28",
      "streamRef": "rtsp://10.1.50.28/main"
    },
    {
      "id": "cam-0-p29",
      "ordinal": 0,
      "at": [
        0.9,
        50.9
      ],
      "heading": 47,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Bar 2 · PTZ 29",
      "streamRef": "rtsp://10.1.50.29/main"
    },
    {
      "id": "cam-0-p30",
      "ordinal": 0,
      "at": [
        14.1,
        50.9
      ],
      "heading": 133,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Bar 2 · PTZ 30",
      "streamRef": "rtsp://10.1.50.30/main"
    },
    {
      "id": "cam-0-p31",
      "ordinal": 0,
      "at": [
        14.1,
        65.1
      ],
      "heading": 227,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Bar 2 · PTZ 31",
      "streamRef": "rtsp://10.1.50.31/main"
    },
    {
      "id": "cam-0-p32",
      "ordinal": 0,
      "at": [
        1.1,
        66.7
      ],
      "heading": 34,
      "fovDeg": 100,
      "rangeM": 21,
      "kind": "ptz",
      "name": "Backbar Storage · PTZ 32",
      "streamRef": "rtsp://10.1.50.32/main"
    },
    {
      "id": "cam-0-p33",
      "ordinal": 0,
      "at": [
        13.9,
        66.7
      ],
      "heading": 146,
      "fovDeg": 100,
      "rangeM": 21,
      "kind": "ptz",
      "name": "Backbar Storage · PTZ 33",
      "streamRef": "rtsp://10.1.50.33/main"
    },
    {
      "id": "cam-0-p34",
      "ordinal": 0,
      "at": [
        13.9,
        75.3
      ],
      "heading": 214,
      "fovDeg": 100,
      "rangeM": 21,
      "kind": "ptz",
      "name": "Backbar Storage · PTZ 34",
      "streamRef": "rtsp://10.1.50.34/main"
    },
    {
      "id": "cam-0-p35",
      "ordinal": 0,
      "at": [
        16.2,
        24.6
      ],
      "heading": 25,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Main Hall · PTZ 35",
      "streamRef": "rtsp://10.1.50.35/main"
    },
    {
      "id": "cam-0-p36",
      "ordinal": 0,
      "at": [
        123.8,
        24.6
      ],
      "heading": 155,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Main Hall · PTZ 36",
      "streamRef": "rtsp://10.1.50.36/main"
    },
    {
      "id": "cam-0-p37",
      "ordinal": 0,
      "at": [
        123.8,
        75.4
      ],
      "heading": 205,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Main Hall · PTZ 37",
      "streamRef": "rtsp://10.1.50.37/main"
    },
    {
      "id": "cam-0-p38",
      "ordinal": 0,
      "at": [
        16.2,
        75.4
      ],
      "heading": 335,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Main Hall · PTZ 38",
      "streamRef": "rtsp://10.1.50.38/main"
    },
    {
      "id": "cam-0-p39",
      "ordinal": 0,
      "at": [
        65.1,
        38.7
      ],
      "heading": 34,
      "fovDeg": 100,
      "rangeM": 17,
      "kind": "ptz",
      "name": "FOH Mix Booth · PTZ 39",
      "streamRef": "rtsp://10.1.50.39/main"
    },
    {
      "id": "cam-0-p40",
      "ordinal": 0,
      "at": [
        74.9,
        45.3
      ],
      "heading": 214,
      "fovDeg": 100,
      "rangeM": 17,
      "kind": "ptz",
      "name": "FOH Mix Booth · PTZ 40",
      "streamRef": "rtsp://10.1.50.40/main"
    },
    {
      "id": "cam-0-p41",
      "ordinal": 0,
      "at": [
        125.6,
        25.2
      ],
      "heading": 65,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Bar 3 · PTZ 41",
      "streamRef": "rtsp://10.1.50.41/main"
    },
    {
      "id": "cam-0-p42",
      "ordinal": 0,
      "at": [
        139.4,
        25.2
      ],
      "heading": 115,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Bar 3 · PTZ 42",
      "streamRef": "rtsp://10.1.50.42/main"
    },
    {
      "id": "cam-0-p43",
      "ordinal": 0,
      "at": [
        139.4,
        54.8
      ],
      "heading": 245,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Bar 3 · PTZ 43",
      "streamRef": "rtsp://10.1.50.43/main"
    },
    {
      "id": "cam-0-p44",
      "ordinal": 0,
      "at": [
        125.6,
        54.8
      ],
      "heading": 295,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Bar 3 · PTZ 44",
      "streamRef": "rtsp://10.1.50.44/main"
    },
    {
      "id": "cam-0-p45",
      "ordinal": 0,
      "at": [
        0.9,
        76.9
      ],
      "heading": 44,
      "fovDeg": 100,
      "rangeM": 42,
      "kind": "ptz",
      "name": "Stage Left Wing · PTZ 45",
      "streamRef": "rtsp://10.1.50.45/main"
    },
    {
      "id": "cam-0-p46",
      "ordinal": 0,
      "at": [
        24.1,
        76.9
      ],
      "heading": 136,
      "fovDeg": 100,
      "rangeM": 42,
      "kind": "ptz",
      "name": "Stage Left Wing · PTZ 46",
      "streamRef": "rtsp://10.1.50.46/main"
    },
    {
      "id": "cam-0-p47",
      "ordinal": 0,
      "at": [
        24.1,
        99.1
      ],
      "heading": 224,
      "fovDeg": 100,
      "rangeM": 42,
      "kind": "ptz",
      "name": "Stage Left Wing · PTZ 47",
      "streamRef": "rtsp://10.1.50.47/main"
    },
    {
      "id": "cam-0-p48",
      "ordinal": 0,
      "at": [
        0.9,
        99.1
      ],
      "heading": 316,
      "fovDeg": 100,
      "rangeM": 42,
      "kind": "ptz",
      "name": "Stage Left Wing · PTZ 48",
      "streamRef": "rtsp://10.1.50.48/main"
    },
    {
      "id": "cam-0-p49",
      "ordinal": 0,
      "at": [
        26.3,
        76.3
      ],
      "heading": 15,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Stage · PTZ 49",
      "streamRef": "rtsp://10.1.50.49/main"
    },
    {
      "id": "cam-0-p50",
      "ordinal": 0,
      "at": [
        113.7,
        76.3
      ],
      "heading": 165,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Stage · PTZ 50",
      "streamRef": "rtsp://10.1.50.50/main"
    },
    {
      "id": "cam-0-p51",
      "ordinal": 0,
      "at": [
        113.7,
        99.7
      ],
      "heading": 195,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Stage · PTZ 51",
      "streamRef": "rtsp://10.1.50.51/main"
    },
    {
      "id": "cam-0-p52",
      "ordinal": 0,
      "at": [
        26.3,
        99.7
      ],
      "heading": 345,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Stage · PTZ 52",
      "streamRef": "rtsp://10.1.50.52/main"
    },
    {
      "id": "cam-0-p53",
      "ordinal": 0,
      "at": [
        116.1,
        76.6
      ],
      "heading": 29,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Stage Right Wing · PTZ 53",
      "streamRef": "rtsp://10.1.50.53/main"
    },
    {
      "id": "cam-0-p54",
      "ordinal": 0,
      "at": [
        138.9,
        76.6
      ],
      "heading": 151,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Stage Right Wing · PTZ 54",
      "streamRef": "rtsp://10.1.50.54/main"
    },
    {
      "id": "cam-0-p55",
      "ordinal": 0,
      "at": [
        138.9,
        89.4
      ],
      "heading": 209,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "Stage Right Wing · PTZ 55",
      "streamRef": "rtsp://10.1.50.55/main"
    },
    {
      "id": "cam-0-p56",
      "ordinal": 0,
      "at": [
        116.2,
        90.5
      ],
      "heading": 22,
      "fovDeg": 100,
      "rangeM": 27,
      "kind": "ptz",
      "name": "Monitor World · PTZ 56",
      "streamRef": "rtsp://10.1.50.56/main"
    },
    {
      "id": "cam-0-p57",
      "ordinal": 0,
      "at": [
        138.8,
        90.5
      ],
      "heading": 158,
      "fovDeg": 100,
      "rangeM": 27,
      "kind": "ptz",
      "name": "Monitor World · PTZ 57",
      "streamRef": "rtsp://10.1.50.57/main"
    },
    {
      "id": "cam-0-p58",
      "ordinal": 0,
      "at": [
        138.8,
        99.5
      ],
      "heading": 202,
      "fovDeg": 100,
      "rangeM": 27,
      "kind": "ptz",
      "name": "Monitor World · PTZ 58",
      "streamRef": "rtsp://10.1.50.58/main"
    },
    {
      "id": "cam-0-p59",
      "ordinal": 0,
      "at": [
        15.9,
        100.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 1 · PTZ 59",
      "streamRef": "rtsp://10.1.50.59/main"
    },
    {
      "id": "cam-0-p60",
      "ordinal": 0,
      "at": [
        39.1,
        100.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 1 · PTZ 60",
      "streamRef": "rtsp://10.1.50.60/main"
    },
    {
      "id": "cam-0-p61",
      "ordinal": 0,
      "at": [
        39.1,
        124.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 1 · PTZ 61",
      "streamRef": "rtsp://10.1.50.61/main"
    },
    {
      "id": "cam-0-p62",
      "ordinal": 0,
      "at": [
        15.9,
        124.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 1 · PTZ 62",
      "streamRef": "rtsp://10.1.50.62/main"
    },
    {
      "id": "cam-0-p63",
      "ordinal": 0,
      "at": [
        40.9,
        100.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 2 · PTZ 63",
      "streamRef": "rtsp://10.1.50.63/main"
    },
    {
      "id": "cam-0-p64",
      "ordinal": 0,
      "at": [
        64.1,
        100.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 2 · PTZ 64",
      "streamRef": "rtsp://10.1.50.64/main"
    },
    {
      "id": "cam-0-p65",
      "ordinal": 0,
      "at": [
        64.1,
        124.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 2 · PTZ 65",
      "streamRef": "rtsp://10.1.50.65/main"
    },
    {
      "id": "cam-0-p66",
      "ordinal": 0,
      "at": [
        40.9,
        124.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 2 · PTZ 66",
      "streamRef": "rtsp://10.1.50.66/main"
    },
    {
      "id": "cam-0-p67",
      "ordinal": 0,
      "at": [
        65.9,
        100.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 3 · PTZ 67",
      "streamRef": "rtsp://10.1.50.67/main"
    },
    {
      "id": "cam-0-p68",
      "ordinal": 0,
      "at": [
        89.1,
        100.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 3 · PTZ 68",
      "streamRef": "rtsp://10.1.50.68/main"
    },
    {
      "id": "cam-0-p69",
      "ordinal": 0,
      "at": [
        89.1,
        124.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 3 · PTZ 69",
      "streamRef": "rtsp://10.1.50.69/main"
    },
    {
      "id": "cam-0-p70",
      "ordinal": 0,
      "at": [
        65.9,
        124.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Greenroom 3 · PTZ 70",
      "streamRef": "rtsp://10.1.50.70/main"
    },
    {
      "id": "cam-0-p71",
      "ordinal": 0,
      "at": [
        90.9,
        100.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Star Dressing Room · PTZ 71",
      "streamRef": "rtsp://10.1.50.71/main"
    },
    {
      "id": "cam-0-p72",
      "ordinal": 0,
      "at": [
        114.1,
        100.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Star Dressing Room · PTZ 72",
      "streamRef": "rtsp://10.1.50.72/main"
    },
    {
      "id": "cam-0-p73",
      "ordinal": 0,
      "at": [
        114.1,
        124.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Star Dressing Room · PTZ 73",
      "streamRef": "rtsp://10.1.50.73/main"
    },
    {
      "id": "cam-0-p74",
      "ordinal": 0,
      "at": [
        90.9,
        124.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Star Dressing Room · PTZ 74",
      "streamRef": "rtsp://10.1.50.74/main"
    },
    {
      "id": "cam-0-p75",
      "ordinal": 0,
      "at": [
        115.9,
        100.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Ramp Corridor · PTZ 75",
      "streamRef": "rtsp://10.1.50.75/main"
    },
    {
      "id": "cam-0-p76",
      "ordinal": 0,
      "at": [
        139.1,
        100.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Ramp Corridor · PTZ 76",
      "streamRef": "rtsp://10.1.50.76/main"
    },
    {
      "id": "cam-0-p77",
      "ordinal": 0,
      "at": [
        139.1,
        124.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Ramp Corridor · PTZ 77",
      "streamRef": "rtsp://10.1.50.77/main"
    },
    {
      "id": "cam-0-p78",
      "ordinal": 0,
      "at": [
        115.9,
        124.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Ramp Corridor · PTZ 78",
      "streamRef": "rtsp://10.1.50.78/main"
    },
    {
      "id": "cam-0-p79",
      "ordinal": 0,
      "at": [
        15.9,
        125.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Production Office · PTZ 79",
      "streamRef": "rtsp://10.1.50.79/main"
    },
    {
      "id": "cam-0-p80",
      "ordinal": 0,
      "at": [
        39.1,
        125.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Production Office · PTZ 80",
      "streamRef": "rtsp://10.1.50.80/main"
    },
    {
      "id": "cam-0-p81",
      "ordinal": 0,
      "at": [
        39.1,
        149.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Production Office · PTZ 81",
      "streamRef": "rtsp://10.1.50.81/main"
    },
    {
      "id": "cam-0-p82",
      "ordinal": 0,
      "at": [
        15.9,
        149.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Production Office · PTZ 82",
      "streamRef": "rtsp://10.1.50.82/main"
    },
    {
      "id": "cam-0-p83",
      "ordinal": 0,
      "at": [
        40.9,
        125.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Catering Kitchen · PTZ 83",
      "streamRef": "rtsp://10.1.50.83/main"
    },
    {
      "id": "cam-0-p84",
      "ordinal": 0,
      "at": [
        64.1,
        125.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Catering Kitchen · PTZ 84",
      "streamRef": "rtsp://10.1.50.84/main"
    },
    {
      "id": "cam-0-p85",
      "ordinal": 0,
      "at": [
        64.1,
        149.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Catering Kitchen · PTZ 85",
      "streamRef": "rtsp://10.1.50.85/main"
    },
    {
      "id": "cam-0-p86",
      "ordinal": 0,
      "at": [
        40.9,
        149.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Catering Kitchen · PTZ 86",
      "streamRef": "rtsp://10.1.50.86/main"
    },
    {
      "id": "cam-0-p87",
      "ordinal": 0,
      "at": [
        65.9,
        125.9
      ],
      "heading": 45,
      "fovDeg": 360,
      "rangeM": 43,
      "kind": "dome",
      "name": "Cash Room · DOME 87",
      "streamRef": "rtsp://10.1.50.87/main"
    },
    {
      "id": "cam-0-p88",
      "ordinal": 0,
      "at": [
        89.1,
        125.9
      ],
      "heading": 135,
      "fovDeg": 360,
      "rangeM": 43,
      "kind": "dome",
      "name": "Cash Room · DOME 88",
      "streamRef": "rtsp://10.1.50.88/main"
    },
    {
      "id": "cam-0-p89",
      "ordinal": 0,
      "at": [
        89.1,
        149.1
      ],
      "heading": 225,
      "fovDeg": 360,
      "rangeM": 43,
      "kind": "dome",
      "name": "Cash Room · DOME 89",
      "streamRef": "rtsp://10.1.50.89/main"
    },
    {
      "id": "cam-0-p90",
      "ordinal": 0,
      "at": [
        65.9,
        149.1
      ],
      "heading": 315,
      "fovDeg": 360,
      "rangeM": 43,
      "kind": "dome",
      "name": "Cash Room · DOME 90",
      "streamRef": "rtsp://10.1.50.90/main"
    },
    {
      "id": "cam-0-p91",
      "ordinal": 0,
      "at": [
        90.9,
        125.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Staff Break Room · PTZ 91",
      "streamRef": "rtsp://10.1.50.91/main"
    },
    {
      "id": "cam-0-p92",
      "ordinal": 0,
      "at": [
        114.1,
        125.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Staff Break Room · PTZ 92",
      "streamRef": "rtsp://10.1.50.92/main"
    },
    {
      "id": "cam-0-p93",
      "ordinal": 0,
      "at": [
        114.1,
        149.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Staff Break Room · PTZ 93",
      "streamRef": "rtsp://10.1.50.93/main"
    },
    {
      "id": "cam-0-p94",
      "ordinal": 0,
      "at": [
        90.9,
        149.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Staff Break Room · PTZ 94",
      "streamRef": "rtsp://10.1.50.94/main"
    },
    {
      "id": "cam-0-p95",
      "ordinal": 0,
      "at": [
        115.9,
        125.9
      ],
      "heading": 45,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Load-in Dock · PTZ 95",
      "streamRef": "rtsp://10.1.50.95/main"
    },
    {
      "id": "cam-0-p96",
      "ordinal": 0,
      "at": [
        139.1,
        125.9
      ],
      "heading": 135,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Load-in Dock · PTZ 96",
      "streamRef": "rtsp://10.1.50.96/main"
    },
    {
      "id": "cam-0-p97",
      "ordinal": 0,
      "at": [
        139.1,
        149.1
      ],
      "heading": 225,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Load-in Dock · PTZ 97",
      "streamRef": "rtsp://10.1.50.97/main"
    },
    {
      "id": "cam-0-p98",
      "ordinal": 0,
      "at": [
        115.9,
        149.1
      ],
      "heading": 315,
      "fovDeg": 100,
      "rangeM": 43,
      "kind": "ptz",
      "name": "Load-in Dock · PTZ 98",
      "streamRef": "rtsp://10.1.50.98/main"
    },
    {
      "id": "cam-0-p99",
      "ordinal": 0,
      "at": [
        10.7,
        146.7
      ],
      "heading": 255,
      "fovDeg": 110,
      "rangeM": 45,
      "kind": "ptz",
      "name": "West Perimeter · PTZ 99",
      "streamRef": "rtsp://10.1.50.99/main"
    },
    {
      "id": "cam-0-p100",
      "ordinal": 0,
      "at": [
        72.3,
        59.7
      ],
      "heading": 271,
      "fovDeg": 110,
      "rangeM": 45,
      "kind": "ptz",
      "name": "Main Hall · PTZ 100",
      "streamRef": "rtsp://10.1.50.100/main"
    },
    {
      "id": "cam-0-p101",
      "ordinal": 0,
      "at": [
        12.7,
        154.9
      ],
      "heading": 338,
      "fovDeg": 110,
      "rangeM": 45,
      "kind": "ptz",
      "name": "West Perimeter · PTZ 101",
      "streamRef": "rtsp://10.1.50.101/main"
    },
    {
      "id": "cam-0-p102",
      "ordinal": 0,
      "at": [
        64.7,
        62.9
      ],
      "heading": 341,
      "fovDeg": 110,
      "rangeM": 45,
      "kind": "ptz",
      "name": "Main Hall · PTZ 102",
      "streamRef": "rtsp://10.1.50.102/main"
    },
    {
      "id": "cam-0-p103",
      "ordinal": 0,
      "at": [
        62.7,
        66.7
      ],
      "heading": 219,
      "fovDeg": 110,
      "rangeM": 45,
      "kind": "ptz",
      "name": "Main Hall · PTZ 103",
      "streamRef": "rtsp://10.1.50.103/main"
    },
    {
      "id": "cam-0-p104",
      "ordinal": 0,
      "at": [
        124.7,
        66.9
      ],
      "heading": 222,
      "fovDeg": 110,
      "rangeM": 45,
      "kind": "ptz",
      "name": "Main Hall · PTZ 104",
      "streamRef": "rtsp://10.1.50.104/main"
    },
    {
      "id": "cam-1-p1",
      "ordinal": 1,
      "at": [
        15.7,
        1.1
      ],
      "heading": 58,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 1 · PTZ 01",
      "streamRef": "rtsp://10.2.50.1/main"
    },
    {
      "id": "cam-1-p2",
      "ordinal": 1,
      "at": [
        29.3,
        1.1
      ],
      "heading": 122,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 1 · PTZ 02",
      "streamRef": "rtsp://10.2.50.2/main"
    },
    {
      "id": "cam-1-p3",
      "ordinal": 1,
      "at": [
        29.3,
        22.9
      ],
      "heading": 238,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 1 · PTZ 03",
      "streamRef": "rtsp://10.2.50.3/main"
    },
    {
      "id": "cam-1-p4",
      "ordinal": 1,
      "at": [
        30.7,
        1.1
      ],
      "heading": 58,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 2 · PTZ 04",
      "streamRef": "rtsp://10.2.50.4/main"
    },
    {
      "id": "cam-1-p5",
      "ordinal": 1,
      "at": [
        44.3,
        1.1
      ],
      "heading": 122,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 2 · PTZ 05",
      "streamRef": "rtsp://10.2.50.5/main"
    },
    {
      "id": "cam-1-p6",
      "ordinal": 1,
      "at": [
        44.3,
        22.9
      ],
      "heading": 238,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 2 · PTZ 06",
      "streamRef": "rtsp://10.2.50.6/main"
    },
    {
      "id": "cam-1-p7",
      "ordinal": 1,
      "at": [
        45.7,
        1.1
      ],
      "heading": 58,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 3 · PTZ 07",
      "streamRef": "rtsp://10.2.50.7/main"
    },
    {
      "id": "cam-1-p8",
      "ordinal": 1,
      "at": [
        59.3,
        1.1
      ],
      "heading": 122,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 3 · PTZ 08",
      "streamRef": "rtsp://10.2.50.8/main"
    },
    {
      "id": "cam-1-p9",
      "ordinal": 1,
      "at": [
        59.3,
        22.9
      ],
      "heading": 238,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 3 · PTZ 09",
      "streamRef": "rtsp://10.2.50.9/main"
    },
    {
      "id": "cam-1-p10",
      "ordinal": 1,
      "at": [
        60.7,
        1.1
      ],
      "heading": 58,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 4 · PTZ 10",
      "streamRef": "rtsp://10.2.50.10/main"
    },
    {
      "id": "cam-1-p11",
      "ordinal": 1,
      "at": [
        74.3,
        1.1
      ],
      "heading": 122,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 4 · PTZ 11",
      "streamRef": "rtsp://10.2.50.11/main"
    },
    {
      "id": "cam-1-p12",
      "ordinal": 1,
      "at": [
        74.3,
        22.9
      ],
      "heading": 238,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 4 · PTZ 12",
      "streamRef": "rtsp://10.2.50.12/main"
    },
    {
      "id": "cam-1-p13",
      "ordinal": 1,
      "at": [
        75.7,
        1.1
      ],
      "heading": 58,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 5 · PTZ 13",
      "streamRef": "rtsp://10.2.50.13/main"
    },
    {
      "id": "cam-1-p14",
      "ordinal": 1,
      "at": [
        89.3,
        1.1
      ],
      "heading": 122,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 5 · PTZ 14",
      "streamRef": "rtsp://10.2.50.14/main"
    },
    {
      "id": "cam-1-p15",
      "ordinal": 1,
      "at": [
        89.3,
        22.9
      ],
      "heading": 238,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 5 · PTZ 15",
      "streamRef": "rtsp://10.2.50.15/main"
    },
    {
      "id": "cam-1-p16",
      "ordinal": 1,
      "at": [
        90.7,
        1.1
      ],
      "heading": 58,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 6 · PTZ 16",
      "streamRef": "rtsp://10.2.50.16/main"
    },
    {
      "id": "cam-1-p17",
      "ordinal": 1,
      "at": [
        104.3,
        1.1
      ],
      "heading": 122,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 6 · PTZ 17",
      "streamRef": "rtsp://10.2.50.17/main"
    },
    {
      "id": "cam-1-p18",
      "ordinal": 1,
      "at": [
        104.3,
        22.9
      ],
      "heading": 238,
      "fovDeg": 100,
      "rangeM": 32,
      "kind": "ptz",
      "name": "VIP Box 6 · PTZ 18",
      "streamRef": "rtsp://10.2.50.18/main"
    },
    {
      "id": "cam-1-p19",
      "ordinal": 1,
      "at": [
        105.8,
        1
      ],
      "heading": 50,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Mezzanine Bar · PTZ 19",
      "streamRef": "rtsp://10.2.50.19/main"
    },
    {
      "id": "cam-1-p20",
      "ordinal": 1,
      "at": [
        124.2,
        1
      ],
      "heading": 130,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Mezzanine Bar · PTZ 20",
      "streamRef": "rtsp://10.2.50.20/main"
    },
    {
      "id": "cam-1-p21",
      "ordinal": 1,
      "at": [
        124.2,
        23
      ],
      "heading": 230,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Mezzanine Bar · PTZ 21",
      "streamRef": "rtsp://10.2.50.21/main"
    },
    {
      "id": "cam-1-p22",
      "ordinal": 1,
      "at": [
        105.8,
        23
      ],
      "heading": 310,
      "fovDeg": 100,
      "rangeM": 37,
      "kind": "ptz",
      "name": "Mezzanine Bar · PTZ 22",
      "streamRef": "rtsp://10.2.50.22/main"
    },
    {
      "id": "cam-1-p23",
      "ordinal": 1,
      "at": [
        16.3,
        24.2
      ],
      "heading": 8,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Mezzanine Concourse · PTZ 23",
      "streamRef": "rtsp://10.2.50.23/main"
    },
    {
      "id": "cam-1-p24",
      "ordinal": 1,
      "at": [
        123.7,
        24.2
      ],
      "heading": 172,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Mezzanine Concourse · PTZ 24",
      "streamRef": "rtsp://10.2.50.24/main"
    },
    {
      "id": "cam-1-p25",
      "ordinal": 1,
      "at": [
        123.7,
        39.8
      ],
      "heading": 188,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Mezzanine Concourse · PTZ 25",
      "streamRef": "rtsp://10.2.50.25/main"
    },
    {
      "id": "cam-1-p26",
      "ordinal": 1,
      "at": [
        16.3,
        39.8
      ],
      "heading": 352,
      "fovDeg": 100,
      "rangeM": 50,
      "kind": "ptz",
      "name": "Mezzanine Concourse · PTZ 26",
      "streamRef": "rtsp://10.2.50.26/main"
    },
    {
      "id": "cam-1-p27",
      "ordinal": 1,
      "at": [
        15.6,
        51.1
      ],
      "heading": 60,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Mezzanine West · PTZ 27",
      "streamRef": "rtsp://10.2.50.27/main"
    },
    {
      "id": "cam-1-p28",
      "ordinal": 1,
      "at": [
        29.4,
        51.1
      ],
      "heading": 120,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Mezzanine West · PTZ 28",
      "streamRef": "rtsp://10.2.50.28/main"
    },
    {
      "id": "cam-1-p29",
      "ordinal": 1,
      "at": [
        29.4,
        74.9
      ],
      "heading": 240,
      "fovDeg": 100,
      "rangeM": 34,
      "kind": "ptz",
      "name": "Mezzanine West · PTZ 29",
      "streamRef": "rtsp://10.2.50.29/main"
    },
    {
      "id": "cam-1-p30",
      "ordinal": 1,
      "at": [
        110.9,
        60.9
      ],
      "heading": 47,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Mezzanine East · PTZ 30",
      "streamRef": "rtsp://10.2.50.30/main"
    },
    {
      "id": "cam-1-p31",
      "ordinal": 1,
      "at": [
        124.1,
        60.9
      ],
      "heading": 133,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Mezzanine East · PTZ 31",
      "streamRef": "rtsp://10.2.50.31/main"
    },
    {
      "id": "cam-1-p32",
      "ordinal": 1,
      "at": [
        124.1,
        75.1
      ],
      "heading": 227,
      "fovDeg": 100,
      "rangeM": 26,
      "kind": "ptz",
      "name": "Mezzanine East · PTZ 32",
      "streamRef": "rtsp://10.2.50.32/main"
    }
  ],
  "footprints": [
    {
      "ordinal": 0,
      "polygon": [
        [
          0,
          0
        ],
        [
          140,
          0
        ],
        [
          140,
          160
        ],
        [
          0,
          160
        ]
      ]
    },
    {
      "ordinal": 1,
      "polygon": [
        [
          15,
          0
        ],
        [
          125,
          0
        ],
        [
          125,
          76
        ],
        [
          110,
          76
        ],
        [
          110,
          40
        ],
        [
          30,
          40
        ],
        [
          30,
          76
        ],
        [
          15,
          76
        ]
      ]
    }
  ],
  "amenities": [
    {
      "id": "am-1",
      "ordinal": 0,
      "at": [
        75,
        1
      ],
      "kind": "exit",
      "name": "Main Entrance"
    },
    {
      "id": "am-2",
      "ordinal": 0,
      "at": [
        105,
        8
      ],
      "kind": "coatcheck"
    },
    {
      "id": "am-3",
      "ordinal": 0,
      "at": [
        29,
        8
      ],
      "kind": "ticketing"
    },
    {
      "id": "am-4",
      "ordinal": 0,
      "at": [
        7,
        42
      ],
      "kind": "bar"
    },
    {
      "id": "am-5",
      "ordinal": 0,
      "at": [
        7,
        58
      ],
      "kind": "bar"
    },
    {
      "id": "am-6",
      "ordinal": 0,
      "at": [
        132,
        40
      ],
      "kind": "bar"
    },
    {
      "id": "am-7",
      "ordinal": 0,
      "at": [
        102,
        160
      ],
      "kind": "smoking"
    },
    {
      "id": "am-8",
      "ordinal": 0,
      "at": [
        127,
        149
      ],
      "kind": "exit"
    },
    {
      "id": "am-9",
      "ordinal": 1,
      "at": [
        115,
        12
      ],
      "kind": "bar"
    },
    {
      "id": "am-10",
      "ordinal": 1,
      "at": [
        22,
        45
      ],
      "kind": "exit"
    },
    {
      "id": "am-11",
      "ordinal": 1,
      "at": [
        117,
        55
      ],
      "kind": "exit"
    }
  ],
  "fixtures": [
    {
      "id": "fix-gapit",
      "ordinal": 0,
      "kind": "seating",
      "polygon": [
        [
          25,
          62
        ],
        [
          115,
          62
        ],
        [
          115,
          76
        ],
        [
          25,
          76
        ]
      ]
    },
    {
      "id": "fix-bar1",
      "ordinal": 0,
      "kind": "bar",
      "polygon": [
        [
          2,
          36
        ],
        [
          13,
          36
        ],
        [
          13,
          38
        ],
        [
          2,
          38
        ]
      ]
    },
    {
      "id": "fix-bar2",
      "ordinal": 0,
      "kind": "bar",
      "polygon": [
        [
          2,
          52
        ],
        [
          13,
          52
        ],
        [
          13,
          54
        ],
        [
          2,
          54
        ]
      ]
    },
    {
      "id": "fix-bar3",
      "ordinal": 0,
      "kind": "bar",
      "polygon": [
        [
          127,
          26
        ],
        [
          138,
          26
        ],
        [
          138,
          28
        ],
        [
          127,
          28
        ]
      ]
    },
    {
      "id": "fix-boxoffice",
      "ordinal": 0,
      "kind": "counter",
      "polygon": [
        [
          20,
          2
        ],
        [
          38,
          2
        ],
        [
          38,
          3
        ],
        [
          20,
          3
        ]
      ]
    },
    {
      "id": "fix-mezzbar",
      "ordinal": 1,
      "kind": "bar",
      "polygon": [
        [
          107,
          2
        ],
        [
          123,
          2
        ],
        [
          123,
          4
        ],
        [
          107,
          4
        ]
      ]
    }
  ],
  "patrols": [
    {
      "id": "patrol-0",
      "ordinal": 0,
      "name": "Hall & Bars Loop",
      "points": [
        [
          70,
          30
        ],
        [
          20,
          40
        ],
        [
          7,
          42
        ],
        [
          7,
          58
        ],
        [
          7,
          70
        ],
        [
          70,
          50
        ],
        [
          132,
          30
        ],
        [
          132,
          40
        ],
        [
          70,
          70
        ]
      ]
    },
    {
      "id": "patrol-1",
      "ordinal": 1,
      "name": "Mezzanine Loop",
      "points": [
        [
          70,
          12
        ],
        [
          20,
          12
        ],
        [
          22,
          50
        ],
        [
          22,
          65
        ],
        [
          70,
          65
        ],
        [
          117,
          65
        ],
        [
          117,
          45
        ],
        [
          115,
          12
        ]
      ]
    }
  ]
};
